## Load Packages, Silently

In [1]:
## Create a vector of the required packages for this analysis
req_packages <- c("anndataR", "ape", "Biostrings", "BSgenome",  "clevr", "cowplot", "GenomicFeatures", "ggplot2", "ggpubr", "ggtree",
                  "gridExtra", "janitor", "nlme", "MAST", "patchwork", "presto", "RColorBrewer", "rhdf5", "Seurat", "stringr", 
                  "tidyverse", "treeio", "TreeTools", "txdbmaker", "vegan", "zellkonverter")

## load the packages, quietly
invisible(suppressWarnings(suppressMessages(
    lapply(req_packages, require, character.only = TRUE)
)))

## Identify variants in D. pseudoobscura mutant

### Set up Data

In [2]:
## load in vep results
raw_variants <- read_tsv("../workflow/tools/VEP/variant_effect_output.txt", skip = 95) %>%
    janitor::clean_names()

## clean up the column information
all_variants <- raw_variants %>%
    separate_wider_delim(extra, ";", names = c("impact", "distance", "strand", "class", "symbol", "biotype"), 
                         too_few = "align_start", too_many = "drop") %>%
    mutate(biotype = case_when(grepl("BIOTYPE", symbol) ~ symbol,
                               TRUE ~ biotype),
           symbol = case_when(grepl("SYMBOL", class) ~ class,
                              TRUE ~ symbol),
           class = case_when(grepl("VARIANT_CLASS", distance) ~ distance,
                             grepl("VARIANT_CLASS", strand) ~ strand,
                             TRUE ~ class),
           strand = case_when(grepl("STRAND", distance) ~ distance,
                              TRUE ~ strand),
           distance = case_when(!grepl("DISTANCE", distance) ~ NA,
                                TRUE ~ distance)) %>%
    mutate(across(everything(), ~ str_replace(., ".*=", ""))) %>%
    separate_wider_delim(number_uploaded_variation, "_", names = c("chromosome", "position", "change"), too_few = "align_start", too_many = "drop") %>%
    mutate(position = as.integer(position))

## filter for only variants on the XR
variants <- all_variants %>%
    filter(grepl("ChrX", chromosome)) %>%
    filter(grepl("ChrX.1", chromosome) | grepl("ChrX.4", chromosome))

## visualize clean data
head(variants)

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 5891958 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (14): #Uploaded_variation, Location, Allele, Gene, Feature, Feature_type...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  chromosome position change location         allele gene feature feature_type
1 ChrX.1     1173     G/A    ChrX.1:1173      A      -    -       -
2 ChrX.1     8650     A/T    ChrX.1:8650      T      -    -       -
3 ChrX.1     9376     T/C    ChrX.1:9376      C      -    -       -
4 ChrX.1     9421     -/T    ChrX.1:9420-9421 T      -    -       -
5 ChrX.1     9423     A/C    ChrX.1:9423      C      -    -       -
6 ChrX.1     9441     T/C    ChrX.1:9441      C      -    -       -
  consequence        c_dna_position ⋯ protein_position amino_acids codons
1 intergenic_variant -              ⋯ -                -           -
2 intergenic_variant -              ⋯ -                -           -
3 intergenic_variant -              ⋯ -                -           -
4 intergenic_variant -              ⋯ -                -           -
5 intergenic_variant -              ⋯ -                -           -
6 intergenic_variant -              ⋯ -                -           -
  existing_variation impact   distance strand class     symbol biotype
1 -                  MODIFIER NA       NA     SNV       NA     NA
2 -                  MODIFIER NA       NA     SNV       NA     NA
3 -                  MODIFIER NA       NA     SNV       NA     NA
4 -                  MODIFIER NA       NA     insertion NA     NA
5 -                  MODIFIER NA       NA     SNV       NA     NA
6 -                  MODIFIER NA       NA     SNV       NA     NA

In [3]:
## load in SFP data from Garlovsky et al. 2022
sperm_sfp <- read_csv("input/sperm_sfp_garlovsky(2022).csv")
sfp <- read_csv("input/refined_sfp_garlovsky(2022).csv")

## load in orthologs between D. melanogaster and D. pseudoobscura
mel_ortho <- read_delim("../workflow/trinotate/drosoma_pse_mel.txt", col_names = FALSE)
names(mel_ortho) <- c("dpse", "dmel", "paralog", "score")

## load in tau data
tau <- read.csv("../workflow/yang2018_rnaseq/results/tau_tissue_0.50.csv")
testes_genes <- tau %>%
    filter(tau_tissue == "male_gonad") %>%
    pull("gene")

Rows: 7 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): FBgn, NAME
dbl (2): Accessory glands, Testis

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 68 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): FBgn, Symbol, Chromosome
dbl (1): Abundance

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 13772 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): X1, X2, X3
dbl (1): X4

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Check the summary information for variant effect

In [4]:
## count how many variants
nrow(variants)

[1] 306663

In [5]:
## count the number of SNPs
variants %>%
    filter(class == "SNV") %>%
    nrow()

[1] 240546

In [6]:
## count the number of genes with mutations
variants %>%
    pull("symbol") %>%
    na.omit() %>%
    unique() %>%
    length()

[1] 731

In [7]:
## annotate mutation types
variant_type <- variants %>%
    separate_longer_delim(consequence, delim = ",") %>%
    mutate(type = case_when(grepl("UTR", consequence) ~ "UTR",
                            grepl("splice", consequence) ~ "splicing",
                            grepl("intron", consequence) ~ "intron",
                            grepl("frameshift", consequence) ~ "frameshift",
                            grepl("inframe", consequence) ~ "inframe",
                            grepl("start_lost", consequence) | grepl("stop_gained", consequence) ~ "nonsense",
                            grepl("missense", consequence) ~ "missense",
                            grepl("protein_altering", consequence) ~ "protein altering",
                            grepl("stream_gene_variant", consequence) ~ "distal"))

## count how many variants of each type
variant_type_number <- variant_type %>%
    select(type, symbol) %>%
    na.omit() %>%
    unique() %>%
    group_by(type) %>%
    count()
variant_type_number

  type             n
1 UTR              545
2 distal           730
3 frameshift        42
4 inframe          135
5 intron           487
6 missense         369
7 nonsense           8
8 protein altering   4
9 splicing         303

In [8]:
## define regulatory sequences
regulator <- c("upstream_gene_variant", "downstream_gene_variant", "3_prime_UTR_variant", "5_prime_UTR_variant")

## count the number of mutations per gene
multi_mutations <- variants %>%
    separate_longer_delim(consequence, ",") %>%
    filter(biotype == "protein_coding" & consequence != "synonymous_variant") %>%
    mutate(mutation_type = case_when(consequence %in% regulator ~ "Regulatory Element",
                             consequence == "intron_variant" ~ "Intron Variant",
                             grepl("splice", consequence) ~ "Splicing Variant",
                             grepl("inframe", consequence) ~ "Inframe InDel",
                             grepl("frameshift", consequence) ~ "Frameshift InDel",
                             consequence == "protein_altering_variant" ~ "Protein Altering",
                             consequence == "stop_gained" ~ "Nonsense Mutation",
                             consequence == "start_lost" ~ "Start Lost",
                             TRUE ~ "Other")) %>%
    group_by(mutation_type, symbol) %>%
    reframe(count = n())
head(multi_mutations)

  mutation_type    symbol       count
1 Frameshift InDel LOC117184369 2
2 Frameshift InDel LOC26532021  1
3 Frameshift InDel LOC26532600  1
4 Frameshift InDel LOC4805581   2
5 Frameshift InDel LOC4805583   4
6 Frameshift InDel LOC4805584   8

In [9]:
## calculate the limit that 99% of genes are within
cap <- quantile(multi_mutations$count, probs = 0.75)
attributes(cap) <- NULL
cap

[1] 118

In [10]:
## find the highest number of mutations in a single gene
max(multi_mutations$count)

[1] 9615

In [11]:
## find the median number of mutations per gene
median(multi_mutations$count)

[1] 13

### Identify potential mutations of interest

In [12]:
## identify protein altering and nonsense mutations
potential_interest <- variants %>%
    filter(consequence == "protein_altering_variant" | consequence == "stop_gained") %>%
    select(symbol, position, change, consequence) %>%
    unique()
potential_interest

   symbol      position change   consequence
1  LOC6901779   645002  -/AGCCAC protein_altering_variant
2  LOC4815337   893839  G/C      stop_gained
3  LOC6902117  1625489  -/TGT    protein_altering_variant
4  LOC4815785  2706647  G/T      stop_gained
5  LOC4815774  2949241  C/T      stop_gained
6  LOC4815426  3468139  -/ACCAGT protein_altering_variant
7  LOC6902257  4221843  -/TGCTGC protein_altering_variant
8  LOC4815659  4250261  C/A      stop_gained
9  LOC26532021 4393675  T/G      stop_gained
10 LOC4814245  5602934  A/T      stop_gained
11 LOC4814348  6196915  C/A      stop_gained

### Determine if mutations of interest are testis specific and/or sperm proteins

In [13]:
## correct symbol name to shorter name
sperm_sfp$dmel <- c("Idgf3", "Tsf1", "Idgf4", "CG6357", "scpr-C", "NT5E-2", "Pde1c")

## identify the D. pseudoobscura orthologs
sperm_dpse <- sperm_sfp %>%
    inner_join(mel_ortho, by = "dmel") %>%
    select(dpse, NAME) %>%
    rename(sperm_protein = NAME, symbol = dpse)

## correctsymbol name to short name
sfp_x <- sfp %>%
    filter(Chromosome == "X")
sfp_x$dmel <- c("regucalcin", "Tsf1", "CG5162", "Hsc70-3", "Idgf4", "CG18258", "Grp170")

## identify the D. pseudoobscura orthologs
sfp_dpse <- sfp_x %>%
    inner_join(mel_ortho, by = "dmel") %>%
    select(dpse, Symbol) %>%
    rename(sfp = Symbol, symbol = dpse)

## identify expression of genes
tissue_expression <- tau %>%
    select(gene, max_organ, tau_tissue) %>%
    rename(symbol = gene)

In [14]:
## add sperm information to mutation of interest data frame
potential_annotated <- potential_interest %>%
    left_join(sperm_dpse, by = "symbol") %>%
    left_join(sfp_dpse, by = "symbol") %>%
    left_join(tissue_expression, by = "symbol")

potential_annotated

   symbol      position change   consequence              sperm_protein sfp
1  LOC6901779   645002  -/AGCCAC protein_altering_variant NA            NA
2  LOC4815337   893839  G/C      stop_gained              NA            NA
3  LOC6902117  1625489  -/TGT    protein_altering_variant NA            NA
4  LOC4815785  2706647  G/T      stop_gained              NA            NA
5  LOC4815774  2949241  C/T      stop_gained              NA            NA
6  LOC4815426  3468139  -/ACCAGT protein_altering_variant NA            NA
7  LOC6902257  4221843  -/TGCTGC protein_altering_variant NA            NA
8  LOC4815659  4250261  C/A      stop_gained              NA            NA
9  LOC26532021 4393675  T/G      stop_gained              NA            NA
10 LOC4814245  5602934  A/T      stop_gained              NA            NA
11 LOC4814348  6196915  C/A      stop_gained              NA            NA
   max_organ      tau_tissue
1  female_abdomen ambiguous
2  female_gonad   ambiguous
3  female_gonad   ambiguous
4  male_head      ambiguous
5  male_digestive ambiguous
6  female_abdomen ambiguous
7  male_gonad     ambiguous
8  female_thorax  ambiguous
9  male_head      male_head
10 male_head      ambiguous
11 female_gonad   ambiguous

## Characterize gene expression in D. pseudoobscura mutant

### Set up Data

In [15]:
## load in LogFC data
comparison_norm <- read_csv("../workflow/multigenome_rnaseq/results/logfc_normalized.csv")
head(comparison_norm)

New names:
• `` -> `...1`
Rows: 28593 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): gene, comparison, significance, direction, color
dbl (3): ...1, logfc, pvalue

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  ...1 gene        comparison          logfc      pvalue       significance
1 1    HCS66_mgp12 sex ratio_reference -0.7478660 3.116607e-08 significant
2 2    HCS66_mgp12 sex ratio_mutant    -0.6487602 6.394837e-08 significant
3 3    HCS66_mgp12 reference_mutant     0.1097625 9.912583e-01 not significant
4 4    HCS66_mgp11 sex ratio_reference -1.4785039 1.809080e-08 significant
5 5    HCS66_mgp11 sex ratio_mutant    -0.9880289 7.678211e-07 significant
6 6    HCS66_mgp11 reference_mutant     0.5010003 1.917109e-03 significant
  direction color
1 hypo      marginally differentially expressed
2 hypo      marginally differentially expressed
3 hyper     not significant
4 hypo      marginally differentially expressed
5 hypo      marginally differentially expressed
6 hyper     marginally differentially expressed

In [16]:
### create database for genes from GFF
dpse_ranges <- makeTxDbFromGFF("/home/yahmed-labshare/data/genomes/obscura_group/pseudoobscura/GCF_009870125.1/genomic.gff", format = "gff")

### load in fasta of pseudoobscura
dpse_fasta <- readDNAStringSet("/home/yahmed-labshare/data/genomes/obscura_group/pseudoobscura/GCF_009870125.1/GCF_009870125.1_UCI_Dpse_MV25_genomic.fna")

Import genomic features from the file as a GRanges object ...

OK

Prepare the 'metadata' data frame ...
OK

Make the TxDb object ...
Warning message in .extract_transcripts_from_GRanges(tx_IDX, gr, mcols0$type, mcols0$ID, :
“some transcripts have no "transcript_id" attribute ==> their name
  ("tx_name" column in the TxDb object) was set to NA”
Warning message in .extract_transcripts_from_GRanges(tx_IDX, gr, mcols0$type, mcols0$ID, :
“the transcript names ("tx_name" column in the TxDb object) imported
  from the "transcript_id" attribute are not unique”
OK

In [17]:
## load in results of Trinotate
ontology <- read_csv("../workflow/trinotate/dpse_goterms.csv") %>%
    select(-1)
head(ontology)

New names:
• `` -> `...1`
Rows: 915220 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): gene, term, category
dbl (1): ...1

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  gene        term                          category
1 HCS66_mgp01 catalytic activity            molecular_function
2 HCS66_mgp01 cytochrome-c oxidase activity molecular_function
3 HCS66_mgp01 transporter activity          molecular_function
4 HCS66_mgp01 binding                       molecular_function
5 HCS66_mgp01 copper ion binding            molecular_function
6 HCS66_mgp01 cellular_component            molecular_function

### Perform GO term analysis

In [18]:
## get list of genes in cluster category
up_genes <- comparison_norm %>%
    filter(comparison == "sex ratio_mutant" & direction == "hypo") %>%
    pull("gene")
down_genes <- comparison_norm %>%
    filter(comparison == "sex ratio_mutant" & direction == "hyper") %>%
    pull("gene")

In [19]:
# ## get list of GO terms
# go_terms <- unique(ontology$term)

# ## Look for GO terms enriched across clusters for each different group

# ## create empty dataframe to populate
# go_compared <- data.frame(go_term = character(),
#                           direction = character(),
#                           go_genes = double(),
#                           go_ratio = double(),
#                           go_pvalue = double())

# for (i in go_terms) {
    
#     ## format dataframe based on mutation type and associated go term
#     go_df <- ontology %>%
#         mutate(signif = case_when(gene %in% up_genes ~ "signif",
#                                   TRUE ~ "nontype"),
#                go = case_when(term == i ~ "go",
#                               TRUE ~ "nogo")) %>%
#         group_by(signif, go) %>%
#         count() %>%
#         pivot_wider(names_from = go, values_from = n) %>%
#         column_to_rownames("signif") %>%
#         mutate_all(replace_na, replace = 0)

#     ## get the number of genes with both mutation type and go term
#     signif_go <- go_df["signif", "go"]

#     ## only perform chi squared if there are more than 0 genes with go term
#     if (signif_go > 0) {        
        
#         ## perform chi-squared test
#         go_chi <- go_df %>%
#             as.matrix() %>%
#             chisq.test()
#         go_pvalue <- go_chi$p.value

#         ## populate dataframe with data
#         go_compared <- add_row(go_compared, go_term = i, 
#                                             direction = "up",
#                                             go_genes = signif_go, 
#                                             go_ratio = signif_go/length(up_genes), 
#                                             go_pvalue = go_pvalue)
        
#     } 

#     ## repeat for adaptive
#     go_df <- ontology %>%
#         mutate(signif = case_when(gene %in% down_genes ~ "signif",
#                                   TRUE ~ "nontype"),
#                go = case_when(term == i ~ "go",
#                               TRUE ~ "nogo")) %>%
#         group_by(signif, go) %>%
#         count() %>%
#         pivot_wider(names_from = go, values_from = n) %>%
#         column_to_rownames("signif") %>%
#         mutate_all(replace_na, replace = 0)
#     signif_go <- go_df["signif", "go"]

#     if (signif_go > 0) {        
#         go_chi <- go_df %>%
#             as.matrix() %>%
#             chisq.test()
#         go_pvalue <- go_chi$p.value
#         go_compared <- add_row(go_compared, go_term = i, 
#                                             direction = "down",
#                                             go_genes = signif_go, 
#                                             go_ratio = signif_go/length(down_genes), 
#                                             go_pvalue = go_pvalue)
#     } 

# }

# ## perform multiple testing correction
# go_compared$pvalue_corrected <- p.adjust(go_compared$go_pvalue, method = "BH")

# write.csv(go_compared, "intermediate/pseudoobscura_mutant_go.csv")

In [20]:
# ## identify genes that are differentially expressed and contain enriched GO terms
# mel_ortho %>%
#     rename(gene = dpse) %>%
#     full_join(ontology, by = "gene", relationship = "many-to-many") %>%
#     select(gene, dmel, paralog, term) %>%
#     filter(gene %in% up_genes & term == "structural molecule activity") %>%
#     unique()

### Identify enrichment among differentially expressed genes

#### Identify testes specific enrichment

In [21]:
## chi squared for all differentially expressed genes
chisq_testes <- comparison_norm %>%
    mutate(testes = case_when(gene %in% testes_genes ~ "testes",
                              TRUE ~ "other")) %>%
    filter(comparison == "sex ratio_mutant") %>%
    group_by(testes, significance) %>%
    count() %>%
    pivot_wider(names_from = significance, values_from = n) %>%
    column_to_rownames("testes") %>%
    as.matrix() %>%
    chisq.test()
chisq_testes$p.value

[1] 2.085023e-05

In [22]:
## chi squared for different differentially expressed genes
chisq_up_testes <- comparison_norm %>%
    filter(comparison == "sex ratio_mutant") %>%
    mutate(testes = case_when(gene %in% testes_genes ~ "testes",
                              TRUE ~ "other"),
           increased = case_when(significance == "significant" & direction == "hypo" ~ "increased",
                                 TRUE ~ "other")) %>%
    group_by(testes, increased) %>%
    count() %>%
    pivot_wider(names_from = increased, values_from = n) %>%
    column_to_rownames("testes") %>%
    as.matrix() %>%
    chisq.test()
chisq_up_testes$p.value
chisq_down_testes <- comparison_norm %>%
    filter(comparison == "sex ratio_mutant") %>%
    mutate(testes = case_when(gene %in% testes_genes ~ "testes",
                              TRUE ~ "other"),
           increased = case_when(significance == "significant" & direction == "hyper" ~ "increased",
                                 TRUE ~ "other")) %>%
    group_by(testes, increased) %>%
    count() %>%
    pivot_wider(names_from = increased, values_from = n) %>%
    column_to_rownames("testes") %>%
    as.matrix() %>%
    chisq.test()
chisq_down_testes$p.value

[1] 2.428335e-109

[1] 7.451586e-176

In [23]:
## chi squared for all differentially expressed genes with reference, as control
chisq_testes <- comparison_norm %>%
    mutate(testes = case_when(gene %in% testes_genes ~ "testes",
                              TRUE ~ "other")) %>%
    filter(comparison == "reference_mutant") %>%
    group_by(testes, significance) %>%
    count() %>%
    pivot_wider(names_from = significance, values_from = n) %>%
    column_to_rownames("testes") %>%
    as.matrix() %>%
    chisq.test()
chisq_testes$p.value
chisq_testes <- comparison_norm %>%
    mutate(testes = case_when(gene %in% testes_genes ~ "testes",
                              TRUE ~ "other")) %>%
    filter(comparison == "sex ratio_reference") %>%
    group_by(testes, significance) %>%
    count() %>%
    pivot_wider(names_from = significance, values_from = n) %>%
    column_to_rownames("testes") %>%
    as.matrix() %>%
    chisq.test()
chisq_testes$p.value

[1] 8.248402e-07

[1] 0.3035263

#### Identify chromosome specific enrichment

In [24]:
## create GRanges object of all of the genes
genes <- genes(dpse_ranges)

## get list of differentially expresed genes
diff_genes <- comparison_norm %>%
    filter(significance == "significant") %>%
    pull("gene")

## get list of genes in each category 
upregulated_genes <- comparison_norm %>%
    filter(comparison == "sex ratio_mutant" & direction == "hypo" & significance == "significant") %>%
    pull("gene")
downregulated_genes <- comparison_norm %>%
    filter(comparison == "sex ratio_mutant" & direction == "hyper" & significance == "significant") %>%
    pull("gene")

## clean up fasta names
fasta_names <- names(dpse_fasta) %>%
    as.data.frame() %>%
    rename(original = 1) %>%
    separate_wider_delim(original, delim = ",", names = c("specifics", "scaffold", "sequencing"), cols_remove = FALSE) %>%
    select(-c(scaffold, sequencing)) %>%
    separate_wider_delim(specifics, delim = " ", names = c("name", "genus", "species", "trash1", "strain", "trash2", "chromosome"), 
                         too_many = "merge", too_few = "align_start") %>%
    select(-c(genus, species, trash1, strain)) %>%
    mutate(chromosome = case_when(trash2 == "chromosome" ~ chromosome,
                                  trash2 == "mitochondrion" ~ "mitochondrion",
                                  TRUE ~ "scaffold")) %>%
    select(original, name, chromosome)

## annotate all of the genes with location and expression
gene_characteristics <- genes %>%
    as_tibble() %>%
    select(seqnames, gene_id) %>%
    mutate(diff = case_when(gene_id %in% diff_genes ~ "diff",
                            TRUE ~ "nondiff"),
           dir = case_when(gene_id %in% upregulated_genes ~ "up",
                           gene_id %in% downregulated_genes ~ "down",
                           TRUE ~ "nondiff")) %>%
    rename(name = seqnames) %>%
    left_join(fasta_names, by = "name") %>%
    select(-c(original, name)) %>%
    mutate(x_chr = case_when(chromosome == "X" ~ "x_chr",
                            TRUE ~ "other_chr"))

## find the percentage of genes that are differentially expressed across chromosome
total_genes <- nrow(gene_characteristics)
signif_genes <- gene_characteristics %>%
    filter(diff == "diff") %>%
    nrow()

(signif_genes/total_genes)*100

[1] 42.18009

In [25]:
write_csv(gene_characteristics, "intermediate/gene_chromosome.csv")

In [26]:
## get the percentage of genes on autosomes that are differentially expressed
nonx_genes <- gene_characteristics %>%
    filter(chromosome != "X") %>%
    nrow()
nonx_signif_genes <- gene_characteristics %>%
    filter(chromosome != "X" & diff == "diff") %>%
    nrow()
nonx_down_genes <- gene_characteristics %>%
    filter(chromosome != "X" & dir == "down") %>%
    nrow()

(nonx_signif_genes/nonx_genes)*100
(nonx_down_genes/nonx_genes)*100

[1] 43.51938

[1] 16.25255

In [27]:
## get the percentage of genes on the X chromosome that are differentially expressed
x_genes <- gene_characteristics %>%
    filter(chromosome == "X") %>%
    nrow()
x_signif_genes <- gene_characteristics %>%
    filter(chromosome == "X" & diff == "diff") %>%
    nrow()
x_down_genes <- gene_characteristics %>%
    filter(chromosome == "X" & dir == "down") %>%
    nrow()

(x_signif_genes/x_genes)*100
(x_down_genes/x_genes)*100

[1] 39.80965

[1] 10.71546

In [28]:
## calculate enrichment of differentially expressed genes on X chromosome
x_diff_chi <- gene_characteristics %>%
    select(gene_id, diff, x_chr) %>%
    group_by(diff, x_chr) %>%
    count() %>%
    pivot_wider(names_from = diff, values_from = n) %>%
    column_to_rownames("x_chr") %>%
    as.matrix() %>%
    chisq.test()
x_diff_chi$p.value

[1] 2.992799e-06

In [29]:
## calculate enrichment of downregulated genes on X chromosome
up_diff_chi <- gene_characteristics %>%
    select(gene_id, dir, x_chr) %>%
    group_by(dir, x_chr) %>%
    filter(dir != "up") %>%
    count() %>%
    pivot_wider(names_from = dir, values_from = n) %>%
    column_to_rownames("x_chr") %>%
    as.matrix() %>%
    chisq.test()
up_diff_chi$p.value

[1] 7.862772e-22

In [30]:
## calculate enrichment of upregulated genes on X chromosome
down_diff_chi <- gene_characteristics %>%
    select(gene_id, dir, x_chr) %>%
    group_by(dir, x_chr) %>%
    filter(dir != "down") %>%
    count() %>%
    pivot_wider(names_from = dir, values_from = n) %>%
    column_to_rownames("x_chr") %>%
    as.matrix() %>%
    chisq.test()
down_diff_chi$p.value

[1] 0.5474331

#### Identify intersection of testes specificity and X chromosome position

In [31]:
## find if enriched in all differentially expressed genes
all_xtest <- gene_characteristics %>%
    mutate(xtest = case_when(x_chr == x_chr & gene_id %in% testes_genes ~ "yes",
                             TRUE ~ "no")) %>%
    group_by(diff,xtest) %>%
    count() %>%
    pivot_wider(names_from = diff, values_from = n) %>%
    column_to_rownames("xtest") %>%
    as.matrix() %>%
    chisq.test()
all_xtest$p.value

[1] 2.555237e-133

In [32]:
## find if enriched in down genes
up_xtest <- gene_characteristics %>%
    filter(dir != "up") %>%
    mutate(xtest = case_when(x_chr == x_chr & gene_id %in% testes_genes ~ "yes",
                             TRUE ~ "no")) %>%
    group_by(dir, xtest) %>%
    count() %>%
    pivot_wider(names_from = dir, values_from = n) %>%
    column_to_rownames("xtest") %>%
    as.matrix() %>%
    chisq.test()
up_xtest$p.value

down_xtest <- gene_characteristics %>%
    filter(dir != "down") %>%
    mutate(xtest = case_when(x_chr == x_chr & gene_id %in% testes_genes ~ "yes",
                             TRUE ~ "no")) %>%
    group_by(dir ,xtest) %>%
    count() %>%
    pivot_wider(names_from = dir, values_from = n) %>%
    column_to_rownames("xtest") %>%
    as.matrix() %>%
    chisq.test()
down_xtest$p.value

[1] 3.097983e-311

[1] 1.072472e-08

## Associate Genes with parasperm content across obscura Group

### Set up Data

In [33]:
## load in results from CAGEE
credible_df <- read_csv("../workflow/tools/CAGEE/credible_genes.csv") %>%
    mutate(across(everything(), ~ str_replace(., "\\*", "")),
           mutate(across(starts_with("x"), ~ as.numeric(.x))),
           sign = case_when(signif == 14 ~ x_14,
                            signif == 15 ~ x_15,
                            signif == 12 ~ x_12)) %>%
    na.omit()

Rows: 563 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): transcript_id, x_12, x_14, x_15
num (1): signif

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [34]:
## load in gene expression data
raw_reads <- read_tsv("../workflow/tools/obscura_group_reads.tsv") %>%
    janitor::clean_names() %>%
    as.data.frame() %>%
    select(-desc)

## load in tree
tree <- ape::read.tree("../workflow/tools/select_obscura_tree.nwk")

Rows: 16880 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): DESC, Gene_ID
dbl (8): Drosophila_affinis, Drosophila_azteca, Drosophila_bifasciata, Droso...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [35]:
## load in parasperm information
parasperm <- read_csv("../workflow/tools/parasperm_proportion.csv", skip = 1) %>%
    janitor::clean_names() %>%
    mutate(species = str_replace(species, "D. ", "Drosophila_")) %>%
    rename(parasperm = 2) %>%
    select(species, parasperm)

New names:
• `` -> `...5`
Rows: 10 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): species, Category, Remating in days (from Holman et al 2007 Evoluti...
dbl (1): % Parasperm

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [36]:
## load motif results
credible_motifs <- read_tsv("../workflow/tools/STREME/streme_credible/sequences.tsv") %>%
    janitor::clean_names()
credible_targets <- read_tsv("../workflow/tools/STREME/streme_credible/tomtom.tsv") %>%
    janitor::clean_names()

head(credible_motifs)
head(credible_targets)

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 13350 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): motif_ID, motif_ALT_ID, seq_ID, seq_Class
dbl (3): motif_P-value, seq_Score, is_holdout?

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 81 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (5): Query_ID, Target_ID, Query_consensus, Target_consensus, Orientation
dbl (5): Optimal_offset, p-value, E-value, q-value, Overlap

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  motif_id      motif_alt_id motif_p_value seq_id      seq_score seq_class
1 1-GGGGGGGGACG STREME-1     0.0078        LOC13036322 21.15     tp
2 1-GGGGGGGGACG STREME-1     0.0078        LOC6903534  21.15     tp
3 1-GGGGGGGGACG STREME-1     0.0078        LOC4815230  21.15     fp
4 1-GGGGGGGGACG STREME-1     0.0078        LOC4817549  21.15     fp
5 1-GGGGGGGGACG STREME-1     0.0078        LOC26534045 21.15     fp
6 1-GGGGGGGGACG STREME-1     0.0078        LOC6898840  21.15     fp
  is_holdout
1 0
2 0
3 0
4 0
5 0
6 0

  query_id      target_id     optimal_offset p_value     e_value    q_value
1 1-GGGGGGGGACG FBgn0086910   5              4.43841e-07 0.00062981 0.00124231
2 1-GGGGGGGGACG FBgn0086910_2 4              2.06429e-05 0.02929230 0.01643510
3 1-GGGGGGGGACG FBgn0036179   2              2.34871e-05 0.03332820 0.01643510
4 1-GGGGGGGGACG OTF0481.1     2              2.34871e-05 0.03332820 0.01643510
5 1-GGGGGGGGACG FBgn0020309   2              3.72195e-05 0.05281440 0.02001810
6 1-GGGGGGGGACG OTF0361.1     0              4.29114e-05 0.06089130 0.02001810
  overlap query_consensus target_consensus     orientation
1 11      GGGGGGGGACG     GGGGGGGGGGGGGACGTGT  +
2 11      GGGGGGGGACG     GGGGGGGGGGGGGGG      +
3 11      GGGGGGGGACG     GGGGGGGGGGGGGGGATAAT +
4 11      GGGGGGGGACG     GGGGGGGGGGGGGGGATAAT +
5 11      GGGGGGGGACG     GGGGAGGGGGGGGGT      -
6 11      GGGGGGGGACG     GGGGGGGGGGG          +

### Characterize credible genes

In [37]:
## get genes with credible changes at nodes with increases in gene expression (without conflicting if present in multiple)
credible_genes <- credible_df %>%
    pull("transcript_id")
length(unique(credible_genes))

[1] 561

In [38]:
## get the direction of the differentially expressed genes
credible_signs <- credible_df %>%
    mutate(direction = case_when(sign > 0 ~ "up",
                                 sign < 0 ~ "down")) %>%
    group_by(direction) %>%
    count()
credible_signs

  direction n
1 down      540
2 up         21

In [39]:
## get list of genes with all the same direction
credible_down_genes <- credible_df %>%
    filter(sign < 0) %>%
    pull("transcript_id")
length(credible_down_genes)

[1] 540

### Determine if there is enrichment for branch associated genes on X or in testes specificity

In [40]:
## add additional gene characteristics
add_gene_char <- gene_characteristics %>%
    mutate(credible = case_when(gene_id %in% credible_down_genes ~ "credible",
                                TRUE ~ "other"),
           testes = case_when(gene_id %in% testes_genes ~ "testes",
                              TRUE ~ "other"))
head(add_gene_char)

  gene_id     diff dir chromosome    x_chr     credible testes
1 HCS66_mgp01 diff up  mitochondrion other_chr other    other
2 HCS66_mgp02 diff up  mitochondrion other_chr other    other
3 HCS66_mgp03 diff up  mitochondrion other_chr other    other
4 HCS66_mgp04 diff up  mitochondrion other_chr other    other
5 HCS66_mgp05 diff up  mitochondrion other_chr other    other
6 HCS66_mgp06 diff up  mitochondrion other_chr other    other

In [41]:
## calculate enrichment of downregulated genes on X chromosome
credible_testes_chi <- add_gene_char %>%
    group_by(credible, testes) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("testes") %>%
    as.matrix() %>%
    chisq.test()
credible_testes_chi$p.value

add_gene_char %>%
    filter(credible == "credible") %>%
    group_by(testes) %>%
    count()

[1] 0

  testes n
1 other   91
2 testes 449

In [42]:
tau %>%
    filter(gene %in% credible_down_genes & tau_tissue == "ambiguous") %>%
    group_by(max_organ) %>%
    count()

  max_organ        n
1 female_abdomen    7
2 female_digestive  4
3 female_gonad      7
4 female_rt         3
5 male_digestive    1
6 male_gonad       56
7 male_rt           2
8 male_thorax       3

In [43]:
## calculate enrichment of downregulated genes on X chromosome
credible_x_chi <- add_gene_char %>%
    group_by(credible, x_chr) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("x_chr") %>%
    as.matrix() %>%
    chisq.test()
credible_x_chi$p.value

add_gene_char %>%
    filter(credible == "credible") %>%
    group_by(chromosome) %>%
    count()

[1] 0.4362217

  chromosome n
1 2           99
2 3           58
3 4          175
4 5            3
5 X          204
6 scaffold     1

### Identify GO terms that are enriched among branch associated genes

In [44]:
# ## Look for GO terms enriched across clusters for each different group

# ## get the list of GO terms
# go_terms <- unique(ontology$term)

# ## create empty dataframe to populate
# go_compared <- data.frame(go_term = character(),
#                           go_genes = double(),
#                           go_ratio = double(),
#                           go_pvalue = double())

# for (i in go_terms) {
    
#     ## format dataframe based on mutation type and associated go term
#     go_df <- ontology %>%
#         mutate(signif = case_when(gene %in% credible_down_genes ~ "signif",
#                                   TRUE ~ "nontype"),
#                go = case_when(term == i ~ "go",
#                               TRUE ~ "nogo")) %>%
#         group_by(signif, go) %>%
#         count() %>%
#         pivot_wider(names_from = go, values_from = n) %>%
#         column_to_rownames("signif") %>%
#         mutate_all(replace_na, replace = 0)

#     ## get the number of genes with both mutation type and go term
#     signif_go <- go_df["signif", "go"]

#     ## only perform chi squared if there are more than 0 genes with go term
#     if (signif_go > 0) {        
        
#         ## perform chi-squared test
#         go_chi <- go_df %>%
#             as.matrix() %>%
#             chisq.test()
#         go_pvalue <- go_chi$p.value

#         ## populate dataframe with data
#         go_compared <- add_row(go_compared, go_term = i, 
#                                             go_genes = signif_go, 
#                                             go_ratio = signif_go/length(credible_down_genes), 
#                                             go_pvalue = go_pvalue)
        
#     } 
# }

# ## perform multiple testing correction
# go_compared$pvalue_corrected <- p.adjust(go_compared$go_pvalue, method = "BH")

# write.csv(go_compared, "intermediate/credible_go.csv")

In [45]:
## investigate the genes that drive the enrichment of the nuclear envelope
ontology %>%
    filter(gene %in% credible_down_genes & grepl("nuclear envelope", term)) %>%
    rename(dpse = gene) %>%
    left_join(mel_ortho, by = "dpse")

   dpse         term
1  LOC117184964 nuclear envelope
2  LOC117184964 nuclear envelope organization
3  LOC117184964 nuclear envelope organization
4  LOC117184964 nuclear envelope
5  LOC117184964 nuclear envelope
6  LOC117184964 nuclear envelope organization
7  LOC4812921   nuclear envelope
8  LOC4812921   nuclear envelope
9  LOC4812921   nuclear envelope
10 LOC4817292   nuclear envelope
11 LOC4817292   nuclear envelope organization
12 LOC4817292   nuclear envelope organization
13 LOC4817292   nuclear envelope
14 LOC4817292   nuclear envelope
15 LOC4817292   nuclear envelope organization
16 LOC4817292   meiotic attachment of telomere to nuclear envelope
17 LOC4817292   chromosome attachment to the nuclear envelope
18 LOC6898244   nuclear envelope
19 LOC6898244   nuclear envelope
20 LOC6898244   nuclear envelope
21 LOC6898991   nuclear envelope
22 LOC6898991   nuclear envelope
23 LOC6898991   nuclear envelope
24 LOC6899211   nuclear envelope
25 LOC6899211   nuclear envelope
26 LOC6899211   nuclear envelope
27 LOC6901712   nuclear envelope
28 LOC6901712   nuclear envelope
29 LOC6901712   nuclear envelope
30 LOC6902410   nuclear envelope
31 LOC6902410   nuclear envelope
32 LOC6902410   nuclear envelope
33 LOC6902412   nuclear envelope
34 LOC6902412   nuclear envelope
35 LOC6902412   nuclear envelope
36 LOC6902453   nuclear envelope
37 LOC6902453   nuclear envelope
38 LOC6902453   nuclear envelope
39 LOC6902458   nuclear envelope
40 LOC6902458   nuclear envelope
41 LOC6902458   nuclear envelope
42 LOC6903274   nuclear envelope
43 LOC6903274   nuclear envelope
44 LOC6903274   nuclear envelope
45 LOC6903594   nuclear envelope
46 LOC6903594   nuclear envelope
47 LOC6903594   nuclear envelope
   category           dmel   paralog score
1  molecular_function NA     NA         NA
2  molecular_function NA     NA         NA
3  biological_process NA     NA         NA
4  biological_process NA     NA         NA
5  cellular_component NA     NA         NA
6  cellular_component NA     NA         NA
7  molecular_function Patj   n:1     20438
8  biological_process Patj   n:1     20438
9  cellular_component Patj   n:1     20438
10 molecular_function NA     NA         NA
11 molecular_function NA     NA         NA
12 biological_process NA     NA         NA
13 biological_process NA     NA         NA
14 cellular_component NA     NA         NA
15 cellular_component NA     NA         NA
16 cellular_component NA     NA         NA
17 cellular_component NA     NA         NA
18 molecular_function Parp16 1:1      7191
19 biological_process Parp16 1:1      7191
20 cellular_component Parp16 1:1      7191
21 molecular_function Cht12  n:1        NA
22 biological_process Cht12  n:1        NA
23 cellular_component Cht12  n:1        NA
24 molecular_function NA     NA         NA
25 biological_process NA     NA         NA
26 cellular_component NA     NA         NA
27 molecular_function NA     NA         NA
28 biological_process NA     NA         NA
29 cellular_component NA     NA         NA
30 molecular_function NA     NA         NA
31 biological_process NA     NA         NA
32 cellular_component NA     NA         NA
33 molecular_function NA     NA         NA
34 biological_process NA     NA         NA
35 cellular_component NA     NA         NA
36 molecular_function NA     NA         NA
37 biological_process NA     NA         NA
38 cellular_component NA     NA         NA
39 molecular_function NA     NA         NA
40 biological_process NA     NA         NA
41 cellular_component NA     NA         NA
42 molecular_function NA     NA         NA
43 biological_process NA     NA         NA
44 cellular_component NA     NA         NA
45 molecular_function NA     NA         NA
46 biological_process NA     NA         NA
47 cellular_component NA     NA         NA

In [46]:
## investigate the genes that drive the enrichment of FFAT motif binding
ontology %>%
    filter(gene %in% credible_down_genes & grepl("FFAT", term)) %>%
    rename(dpse = gene) %>%
    left_join(mel_ortho, by = "dpse")

  dpse       term               category           dmel paralog score
1 LOC6900207 FFAT motif binding cellular_component fan  n:1        NA
2 LOC6902465 FFAT motif binding cellular_component NA   NA         NA
3 LOC6902496 FFAT motif binding cellular_component fan  n:1     30854
4 LOC6902928 FFAT motif binding cellular_component NA   NA         NA

In [47]:
## investigate the genes that drive the enrichment of IRE stress response
ontology %>%
    filter(gene %in% credible_down_genes & grepl("IRE", term)) %>%
    rename(dpse = gene) %>%
    inner_join(mel_ortho, by = "dpse")

  dpse       term                                    category           dmel
1 LOC6900207 IRE1-mediated unfolded protein response cellular_component fan
2 LOC6902496 IRE1-mediated unfolded protein response cellular_component fan
  paralog score
1 n:1        NA
2 n:1     30854

In [48]:
## investigate the genes associated with ER stress response
### IRE
### PERK
mel_ortho %>%
    filter(dpse %in% credible_down_genes & grepl("parp", dmel, ignore.case = TRUE))

  dpse       dmel   paralog score
1 LOC6898244 Parp16 1:1     7191

### Identify motifs enriched among branch-associated genes

In [49]:
credible_motifs %>%
    filter(motif_p_value < 0.05 & seq_id %in% credible_down_genes)

    motif_id       motif_alt_id motif_p_value seq_id       seq_score seq_class
1   1-GGGGGGGGACG  STREME-1     0.0078        LOC13036322  21.15     tp
2   1-GGGGGGGGACG  STREME-1     0.0078        LOC6903534   21.15     tp
3   1-GGGGGGGGACG  STREME-1     0.0078        LOC117184593 19.76     tp
4   1-GGGGGGGGACG  STREME-1     0.0078        LOC26533335  19.76     tp
5   1-GGGGGGGGACG  STREME-1     0.0078        LOC117184603 19.76     tp
6   1-GGGGGGGGACG  STREME-1     0.0078        LOC6901665   19.76     tp
7   1-GGGGGGGGACG  STREME-1     0.0078        LOC26532845  19.76     tp
8   1-GGGGGGGGACG  STREME-1     0.0078        LOC6901481   19.76     tp
9   1-GGGGGGGGACG  STREME-1     0.0078        LOC6901126   18.44     tp
10  1-GGGGGGGGACG  STREME-1     0.0078        LOC26533304  18.44     tp
11  1-GGGGGGGGACG  STREME-1     0.0078        LOC26532582  18.44     tp
12  1-GGGGGGGGACG  STREME-1     0.0078        LOC6903400   18.44     tp
13  1-GGGGGGGGACG  STREME-1     0.0078        LOC6902823   18.27     tp
14  1-GGGGGGGGACG  STREME-1     0.0078        LOC26534214  18.17     tp
15  1-GGGGGGGGACG  STREME-1     0.0078        LOC26533347  18.15     tp
16  1-GGGGGGGGACG  STREME-1     0.0078        LOC26532598  18.15     tp
17  1-GGGGGGGGACG  STREME-1     0.0078        LOC6900445   18.04     tp
18  1-GGGGGGGGACG  STREME-1     0.0078        LOC26532452  17.54     tp
19  1-GGGGGGGGACG  STREME-1     0.0078        LOC6903213   17.54     tp
20  1-GGGGGGGGACG  STREME-1     0.0078        LOC4817668   17.54     tp
21  1-GGGGGGGGACG  STREME-1     0.0078        LOC6898809   17.54     tp
22  1-GGGGGGGGACG  STREME-1     0.0078        LOC6897928   17.54     tp
23  1-GGGGGGGGACG  STREME-1     0.0078        LOC117184392 17.00     tp
24  1-GGGGGGGGACG  STREME-1     0.0078        LOC6903594   16.97     tp
25  1-GGGGGGGGACG  STREME-1     0.0078        LOC6901551   16.97     tp
26  1-GGGGGGGGACG  STREME-1     0.0078        LOC26533629  16.78     tp
27  1-GGGGGGGGACG  STREME-1     0.0078        LOC117184019 16.78     tp
28  1-GGGGGGGGACG  STREME-1     0.0078        LOC4816726   16.78     tp
29  1-GGGGGGGGACG  STREME-1     0.0078        LOC6897206   16.78     tp
30  1-GGGGGGGGACG  STREME-1     0.0078        LOC6901593   16.78     tp
⋮   ⋮              ⋮            ⋮             ⋮            ⋮         ⋮
236 4-AAAATTTTGTAT STREME-4     0.037         LOC6903261   15.47     tp
237 4-AAAATTTTGTAT STREME-4     0.037         LOC26532910  15.47     tp
238 4-AAAATTTTGTAT STREME-4     0.037         LOC6901797   15.36     tp
239 4-AAAATTTTGTAT STREME-4     0.037         LOC26533942  14.74     tp
240 4-AAAATTTTGTAT STREME-4     0.037         LOC6897896   14.74     tp
241 4-AAAATTTTGTAT STREME-4     0.037         LOC6900274   14.70     tp
242 4-AAAATTTTGTAT STREME-4     0.037         LOC6896757   14.70     tp
243 4-AAAATTTTGTAT STREME-4     0.037         LOC6898217   14.59     tp
244 4-AAAATTTTGTAT STREME-4     0.037         LOC26532678  14.59     tp
245 4-AAAATTTTGTAT STREME-4     0.037         LOC26533531  14.59     tp
246 4-AAAATTTTGTAT STREME-4     0.037         LOC26533523  14.59     tp
247 4-AAAATTTTGTAT STREME-4     0.037         LOC6898004   14.56     tp
248 4-AAAATTTTGTAT STREME-4     0.037         LOC6903336   14.56     tp
249 4-AAAATTTTGTAT STREME-4     0.037         LOC4805490   14.56     tp
250 4-AAAATTTTGTAT STREME-4     0.037         LOC26533465  14.48     tp
251 4-AAAATTTTGTAT STREME-4     0.037         LOC117184597 14.48     tp
252 4-AAAATTTTGTAT STREME-4     0.037         LOC6901350   14.48     tp
253 4-AAAATTTTGTAT STREME-4     0.037         LOC6902021   14.39     tp
254 4-AAAATTTTGTAT STREME-4     0.037         LOC4817215   14.36     tp
255 4-AAAATTTTGTAT STREME-4     0.037         LOC6902534   14.28     tp
256 4-AAAATTTTGTAT STREME-4     0.037         LOC26533027  14.27     tp
257 4-AAAATTTTGTAT STREME-4     0.037         LOC26533322  14.27     tp
258 4-AAAATTTTGTAT STREME-4     0.037         LOC6901816   14.27     tp
259 4-AAAATTTTGTAT STREME-4     0.037         LOC6897928   14.27     tp
260 4-AAAATTTTGTAT STREME-4     0.037         LOC117185159 14.26     tp
261 4-AAAATTTTGTAT STREME-4     0.037         LOC26533148  14.18     tp
262 4-AAAATTTTGTAT STREME-4     0.037         LOC26532220  14.17     tp
263 4-AAAATTTTGTAT STREME-4     0.037         LOC6902241   14.13     tp
264 4-AAAATTTTGTAT STREME-4     0.037         LOC6901153   14.13     tp
265 4-AAAATTTTGTAT STREME-4     0.037         LOC4813116   14.13     tp
    is_holdout
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  0
11  0
12  0
13  0
14  0
15  0
16  0
17  1
18  0
19  0
20  0
21  0
22  1
23  0
24  0
25  0
26  0
27  0
28  0
29  0
30  0
⋮   ⋮
236 0
237 1
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 1
247 0
248 0
249 1
250 0
251 0
252 0
253 0
254 0
255 0
256 0
257 0
258 0
259 1
260 0
261 0
262 0
263 0
264 0
265 1

## Compare parasperm associated genes with mutant information

In [50]:
## perform a PCA on the reads
pca <- raw_reads %>%
    column_to_rownames("gene_id") %>%
    as.matrix() %>%
    t() %>%
    prcomp()
summary(pca)

## determines genes that contribute to variation
pca_loading <- pca$rotation %>%
    as.data.frame() %>%
    select(PC1, PC2, PC3) %>%
    rownames_to_column("gene") %>%
    pivot_longer(!gene, names_to = "pc", values_to = "loading") %>%
    group_by(pc) %>% 
    arrange(desc(abs(loading)))

## get top 20% of genes that explain variance
var_genes <- pca_loading %>%
    slice(1:(length(unique(pca_loading$gene))/5)) %>%
    pull("gene") %>%
    unique()

## reformat reads so each gene is a row and each species is a column
reads <- raw_reads %>%
    filter(gene_id %in% var_genes) %>% ## filter for only the most variable genes
    mutate_at(vars(-gene_id), as.double) %>%
    column_to_rownames("gene_id") %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column("species") %>%
    mutate(species = str_replace(species, "drosophila", "Drosophila")) %>%
    column_to_rownames("species")

## get list of species
species <- rownames(reads)

Importance of components:
                             PC1       PC2       PC3       PC4       PC5
Standard deviation     4.939e+05 4.470e+05 4.065e+05 2.969e+05 2.914e+05
Proportion of Variance 2.814e-01 2.304e-01 1.906e-01 1.017e-01 9.792e-02
Cumulative Proportion  2.814e-01 5.119e-01 7.025e-01 8.042e-01 9.021e-01
                             PC6       PC7       PC8
Standard deviation     2.456e+05 1.567e+05 5.255e-10
Proportion of Variance 6.958e-02 2.833e-02 0.000e+00
Cumulative Proportion  9.717e-01 1.000e+00 1.000e+00

In [51]:
## combine differential expression and parasperm data
annotated_logfc <- colnames(reads) %>%
    as.data.frame() %>%
    rename(gene = 1) %>%
    left_join(comparison_norm, by = "gene") %>%
    filter(comparison == "sex ratio_mutant") %>%
    mutate(logfc = -(logfc),
           credible = case_when(gene %in% credible_down_genes ~ "credible",
                                TRUE ~ "non-credible"),
           significance = case_when(is.na(significance) ~ "not significant",
                                    TRUE ~ significance),
           color = case_when(is.na(color) ~ "not significant",
                             TRUE ~ color),
           direction = case_when(significance == "significant" & logfc < 0 ~ "hypo",
                                 significance == "significant" & logfc > 0 ~ "hyper",
                                 TRUE ~ "not significant"),
           testes_specificity = case_when(gene %in% testes_genes ~ "testes",
                                          TRUE ~ "other"),
           x = case_when(gene %in% x_genes ~ "x",
                         TRUE ~ "other")) %>%
    unique()

### Identify enrichment of parasperm associated genes among differentially expressed genes

In [52]:
## compare number of significant genes to those with credible and adaptive
credible_logfc <- annotated_logfc %>%
    group_by(credible, significance) %>%
    count() %>%
    pivot_wider(names_from = significance, values_from = n) %>%
    column_to_rownames("credible") %>%
    mutate_all(replace_na, replace = 0) %>%
    as.matrix()

## perform chi squared test
chisq.test(credible_logfc)$p.value

[1] 3.660479e-08

In [53]:
## now look at credible, separating increase and decrease
credible_up_mx <- annotated_logfc %>%
    filter(direction != "hypo") %>%
    group_by(credible, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("credible") %>%
    mutate_all(replace_na, replace = 0) %>%
    as.matrix()
credible_up_chi <- chisq.test(credible_up_mx)
credible_up_chi$p.value

credible_down_mx <- annotated_logfc %>%
    filter(direction != "hyper") %>%
    group_by(credible, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("credible") %>%
    mutate_all(replace_na, replace = 0) %>%
    as.matrix()
credible_down_chi <- chisq.test(credible_down_mx)
credible_down_chi$p.value

[1] 8.05134e-07

[1] 4.412681e-28

In [54]:
## identify the expression of credible genes
annotated_logfc %>%
    filter(credible == "credible") %>%
    group_by(direction) %>%
    count()

  direction       n
1 hyper            20
2 hypo            221
3 not significant 112

In [55]:
## get the list of genes whose increase in expression are associated with parasperm content
credible_up_genes <- credible_genes[!(credible_genes %in% credible_down_genes)]
length(credible_up_genes)

## determine the direction of expression of these genes in the mutant
annotated_logfc %>%
    filter(gene %in% credible_up_genes) %>%
    group_by(direction) %>%
    count()

[1] 21

  direction       n
1 hyper           1
2 hypo            6
3 not significant 7

In [56]:
## identify the one gene with differential expression
credible_upup <- annotated_logfc %>%
    filter(gene %in% credible_up_genes & direction == "hyper") %>%
    pull("gene")

## characterize the one gene with increased expression
annotated_logfc %>%
    filter(gene %in% credible_up_genes & direction == "hyper")
mel_ortho %>%
    filter(dpse == credible_upup)
ontology %>%
    filter(gene == credible_upup)

  gene       ...1 comparison       logfc     pvalue       significance
1 LOC6897697 5435 sex ratio_mutant 0.3634016 0.0006169901 significant
  direction color                               credible     testes_specificity
1 hyper     marginally differentially expressed non-credible testes
  x
1 other

     dpse dmel paralog score

     gene term category

### Identify GO terms associated with branch associated genes that are downregulated in the mutant

In [57]:
# ## look for enriched GO terms in for credible, up-regulated genes

# ## get the list of GO terms
# go_terms <- unique(ontology$term)

# ## get list of credible, up-regulated genes
# downcred_genes <- annotated_logfc %>%
#     filter(credible == "credible" & direction == "hypo") %>%
#     pull("gene")

# ## create empty dataframe to populate
# go_compared <- data.frame(go_term = character(),
#                           go_genes = double(),
#                           go_ratio = double(),
#                           go_pvalue = double())

# for (i in go_terms) {    
    
#     ## format dataframe based on associated go term
#     go_df <- ontology %>%
#         mutate(signif = case_when(gene %in% downcred_genes ~ "signif",
#                                     TRUE ~ "nontype"),
#                go = case_when(term == i ~ "go",
#                               TRUE ~ "nogo")) %>%
#         group_by(signif, go) %>%
#         count() %>%
#         pivot_wider(names_from = go, values_from = n) %>%
#         column_to_rownames("signif") %>%
#         mutate_all(replace_na, replace = 0)

#     ## get the number of genes with go term
#     signif_go <- go_df["signif", "go"]

#     ## only perform chi squared if there are more than 0 genes with go term
#     if (signif_go > 0) {        
        
#         ## perform chi-squared test
#         go_chi <- go_df %>%
#             as.matrix() %>%
#             chisq.test()
#         go_pvalue <- go_chi$p.value

#         ## populate dataframe with data
#         go_compared <- add_row(go_compared, go_term = i, 
#                                             go_genes = signif_go, 
#                                             go_ratio = signif_go/length(downcred_genes), 
#                                             go_pvalue = go_pvalue)
        
#     }    
# }

# ## perform multiple testing correction
# go_compared$pvalue_corrected <- p.adjust(go_compared$go_pvalue, method = "BH")

# write.csv(go_compared, "intermediate/credible_down_go.csv")

In [58]:
## investigate the genes that drive the enrichment of specific GO terms
ontology %>%
    filter(gene %in% credible_down_genes & gene %in% down_genes & grepl("immune", term)) %>%
    rename(dpse = gene) %>%
    left_join(mel_ortho, by = "dpse")

   dpse       term                                           category
1  LOC6896671 regulation of innate immune response           cellular_component
2  LOC6896671 regulation of immune response                  cellular_component
3  LOC6897740 immune response                                molecular_function
4  LOC6897740 immune response                                biological_process
5  LOC6897740 immune response                                cellular_component
6  LOC6897740 RNAi-mediated antiviral immune response        cellular_component
7  LOC6897740 innate immune response                         cellular_component
8  LOC6901659 immune response                                molecular_function
9  LOC6901659 immune response                                biological_process
10 LOC6901659 immune response                                cellular_component
11 LOC6901659 innate immune response                         cellular_component
12 LOC6902212 immune response                                molecular_function
13 LOC6902212 immune response                                biological_process
14 LOC6902212 immune response                                cellular_component
15 LOC6902212 innate immune response                         cellular_component
16 LOC6902212 regulation of innate immune response           cellular_component
17 LOC6902212 positive regulation of innate immune response  cellular_component
18 LOC6902212 regulation of immune response                  cellular_component
19 LOC6902212 positive regulation of immune response         cellular_component
20 LOC6903952 regulation of innate immune response           cellular_component
21 LOC6903952 negative regulation of innate immune response  cellular_component
22 LOC6903952 regulation of immune response                  cellular_component
23 LOC6903952 negative regulation of immune response         cellular_component
24 LOC4801448 immune system process                          molecular_function
25 LOC4816148 regulation of immune system process            molecular_function
26 LOC4816866 regulation of immune system process            molecular_function
27 LOC4816866 negative regulation of immune system process   molecular_function
28 LOC4816866 regulation of immune effector process          molecular_function
29 LOC4816866 negative regulation of immune effector process molecular_function
30 LOC6896671 regulation of immune system process            molecular_function
31 LOC6897740 immune effector process                        molecular_function
32 LOC6897740 immune system process                          molecular_function
33 LOC6898990 immune system process                          molecular_function
34 LOC6898991 immune system process                          molecular_function
35 LOC6901659 immune system process                          molecular_function
36 LOC6902212 immune effector process                        molecular_function
37 LOC6902212 immune system process                          molecular_function
38 LOC6902212 regulation of immune system process            molecular_function
39 LOC6902212 positive regulation of immune system process   molecular_function
40 LOC6903952 immune system process                          molecular_function
41 LOC6903952 regulation of immune system process            molecular_function
42 LOC6903952 negative regulation of immune system process   molecular_function
43 LOC6903952 positive regulation of immune system process   molecular_function
   dmel   paralog score
1  CanA1  1:1     18195
2  CanA1  1:1     18195
3  AGO2   n:1        NA
4  AGO2   n:1        NA
5  AGO2   n:1        NA
6  AGO2   n:1        NA
7  AGO2   n:1        NA
8  NA     NA         NA
9  NA     NA         NA
10 NA     NA         NA
11 NA     NA         NA
12 NA     NA         NA
13 NA     NA         NA
14 NA     NA         NA
15 NA     NA         NA
16 NA     NA         NA
17 NA     NA         NA
18 NA     NA         NA
19 NA     NA         NA
20 NA     NA         NA
21 NA     NA         NA
22 NA     NA         NA
23 NA     NA         NA
24 Wdr37  1:1      2151
25 CG9314 1:1     22080
26 CG2617 n:1     27851
27 CG2617 n:1     27851
28 CG2617 n:1     27851
29 CG2617 n:1     27851
30 CanA1  1:1     18195
31 AGO2   n:1        NA
32 AGO2   n:1        NA
33 Cht12  n:1        NA
34 Cht12  n:1        NA
35 NA     NA         NA
36 NA     NA         NA
37 NA     NA         NA
38 NA     NA         NA
39 NA     NA         NA
40 NA     NA         NA
41 NA     NA         NA
42 NA     NA         NA
43 NA     NA         NA

## Analyze single cell data set

### Load data

In [59]:
## load in single-cell RNA-seq results as singlecell experiment
sce_sce <- readH5AD("/home/yahmed-labshare/scratch/pseudoobscura_testis_scRNASeq/pseudo_testis_scRNAseq.h5ad")

# convert single cell experiment to Seurat
sce <- as.Seurat(sce_sce, counts = "counts", data = "X")

Warning message:
“The names of these selected var columns have been modified to match R
conventions: '2' -> 'X2'”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Keys should be one or more alphanumeric characters followed by an underscore, setting key from X_diffmap_ to Xdiffmap_”
Warning message:
“Keys should be one or more alphanumeric characters followed by an underscore, setting key from X_draw_graph_fa_ to Xdrawgraphfa_”
Warning message:
“Keys should be one or more alphanumeric characters followed by an underscore, setting key from X_pca_ to Xpca_”
Warning message:
“Keys should be one or more alphanumeric characters followed by an underscore, setting key from X_tsne_ to Xtsne_”
Warning message:
“Keys should be one or more alphanumeric characters followed by an underscore, setting key from X_umap_ to Xumap_”

In [60]:
## create data frame of genes from He et al. 2026
dmel_he_testis_genes <- data.frame(stage = c("GSC/Spermatogonia", "GSC/Spermatogonia", "GSC/Spermatogonia", "GSC/Spermatogonia", "GSC/Spermatogonia",
                                            "Early Spermatocytes", "Early Spermatocytes", "Early Spermatocytes",
                                            "Late Spermatocytes", "Late Spermatocytes", "Late Spermatocytes",
                                            "Spermatid", "Spermatid",
                                            "Cyst", "Cyst",
                                            "Hub", "Epithelial", "Epithelial"),
                                   dmel = c("AGO3", "aub", "bam", "vas", "aly", "can", "sa", "CycB", "twe", "bol", "soti", "wa-cup", "f-cup",
                                            "tj", "eya", "Fas3", "MtnA", "Hsp23"))

## get the D. pseudoobscura counterpart for each gene
he_testis_genes <- mel_ortho %>%
    select(dmel, dpse) %>%
    right_join(dmel_he_testis_genes, by = "dmel")
head(he_testis_genes)

  dmel   dpse        stage
1 f-cup  LOC6897136  Spermatid
2 soti   LOC4801948  Late Spermatocytes
3 wa-cup LOC4802953  Spermatid
4 bam    LOC4803214  GSC/Spermatogonia
5 CycB   LOC4803852  Early Spermatocytes
6 AGO3   LOC26534190 GSC/Spermatogonia

In [61]:
## create data frame of genes from Messer et al. 2026
dmel_messer_testis_genes <- data.frame(stage = c("GSC-SG", "SG", "SG", "SG",
                                                 "SC", "SC", "SC", "SC", "SC", "SC", "SC", "SC",
                                                 "ST", "ST", "ST"),
                                       dmel = c("esg", "shg", "vas", "aly", 
                                                "wuc", "ProtA", "boule", "TGIF", "kmg", "S-Lap5", "S-Lap7", "S-Lap8",
                                                "f-cup", "wa-cup", "p-cup"))

## get the D. pseudoobscura counterpart for each gene
messer_testis_genes <- mel_ortho %>%
    select(dmel, dpse) %>%
    right_join(dmel_messer_testis_genes, by = "dmel") %>%
    na.omit()
messer_testis_genes

   dmel   dpse       stage
1  f-cup  LOC6897136 ST
2  wa-cup LOC4802953 ST
3  S-Lap5 LOC6898081 SC
4  S-Lap8 LOC4803787 SC
5  wuc    LOC4804758 SC
6  S-Lap7 LOC4805161 SC
7  S-Lap5 LOC4805168 SC
8  shg    LOC6898987 SG
9  esg    LOC4816405 GSC-SG
10 kmg    LOC4816438 SC
11 p-cup  LOC4815368 ST

### Process single cell data

In [62]:
# ## find genes that vary between cells
# sce <- FindVariableFeatures(sce, selection.method = "vst", nfeatures = 2000)

# ## scale data
# gene_list <- rownames(sce)
# scaled_sce <- ScaleData(sce, features = gene_list)

# ## run PCA on counts (pca saved in sce[["pca"]])
# pca_sce <- RunPCA(scaled_sce, features = VariableFeatures(object = scaled_sce))

# ## find clusters, based on the first 30 PCs
# cluster_sce <- FindNeighbors(pca_sce, dims = 1:30)
# cluster_sce <- FindClusters(cluster_sce, resolution = 0.75)

# ## run UMAP and annotate with these clusters
# cluster_sce <- RunUMAP(cluster_sce, dims = 1:30)

# ## save the names of the clusters
# cluster_names <- c("Late EuC (0)", "G (1)", "Late EuC (2)", "Late PaC (3)", "Early EuC (4)", "Late PaC (5)", "Epi (6)", "Late EuC (7)", "Early PaC (8)", "Early EuC (9)", "Early EuC (10)", 
#                    "Early EuC (11)", "Early PaC (12)", "G (13)", "EuS (14)", "Early PaC (15)", "Early EuC (16)", "Late PaC (17)", "PaS (18)", "Late EuC (19)", "Early PaC (20)")
# names(cluster_names) <- levels(cluster_sce)

# ## annotate the clusters
# annotated_sce <- RenameIdents(cluster_sce, cluster_names)

# ## reannotated clusters based on cell type
# cluster_names <- c("Late EuC", "G", "Late EuC", "Late PaC", "Early EuC", "Late PaC", "Epi", "Late EuC", "Early PaC", "Early EuC", "Early EuC", 
#                    "Early EuC", "Early PaC", "G", "EuS", "Early PaC", "Early EuC", "Late PaC", "PaS", "Late EuC", "Early PaC")
# names(cluster_names) <- levels(cluster_sce)

# ## annotate the clusters
# annotated_down_sce <- RenameIdents(cluster_sce, cluster_names)

# ## find markers for the annotated cluster
# sce_markers <- FindAllMarkers(object = annotated_down_sce, only.pos = TRUE, return.thresh = 0.01)

# ## save file 
# write_csv(sce_markers, "intermediate/pseudoobscura_testis_markers.csv")

# ## get the cell stage 
# cell_stages <- Idents(annotated_down_sce) %>%
#     as.data.frame() %>%
#     pull(1)

# ## add metadata column for cell stage
# annotated_down_sce$stage <- cell_stages

# ## save object
# saveRDS(annotated_down_sce, "intermediate/processed_sce.rds")

# ## find differentially expressed genes between eusperm and parasperm for different cell types
# early_c_logfc <- FindMarkers(annotated_down_sce, ident.1 = "Early EuC", ident.2 = "Early PaC", test.use = "MAST") %>%
#     mutate(stage = "early_spermatocyte")
# late_c_logfc <- FindMarkers(annotated_down_sce, ident.1 = "Late EuC", ident.2 = "Late PaC", test.use = "MAST") %>%
#     mutate(stage = "late_spermatocyte")
# sperm_logfc <- FindMarkers(annotated_down_sce, ident.1 = "EuS", ident.2 = "PaS", test.use = "MAST") %>%
#     mutate(stage = "sperm")

# ## combine into data set
# logfc_morph <- rbind(early_c_logfc, late_c_logfc, sperm_logfc) %>%
#     rownames_to_column("gene")
# write_csv(logfc_morph, "intermediate/logfc_morph_stage.csv")

### Identify genes that differ between sperm morphs for each stage of development

In [63]:
## load processed single cell experiment object
sce <- readRDS("intermediate/processed_sce.rds")

## load in logFC between stages data
logfc_morph <- read_csv("intermediate/logfc_morph_stage.csv")

Rows: 29336 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): gene, stage
dbl (5): p_val, avg_log2FC, pct.1, pct.2, p_val_adj

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [64]:
## get the list of genes that are significantly differentially expressed among each stage
ec_eu_genes <- logfc_morph %>%
    filter(stage == "early_spermatocyte" & p_val_adj < 0.01 & avg_log2FC > 0) %>%
    pull("gene")
lc_eu_genes <- logfc_morph %>%
    filter(stage == "late_spermatocyte" & p_val_adj < 0.01 & avg_log2FC > 0) %>%
    pull("gene")
s_eu_genes <- logfc_morph %>%
    filter(stage == "late_spermatocyte" & p_val_adj < 0.01 & avg_log2FC > 0) %>%
    pull("gene")

ec_pa_genes <- logfc_morph %>%
    filter(stage == "early_spermatocyte" & p_val_adj < 0.01 & avg_log2FC < 0) %>%
    pull("gene")
lc_pa_genes <- logfc_morph %>%
    filter(stage == "late_spermatocyte" & p_val_adj < 0.01 & avg_log2FC < 0) %>%
    pull("gene")
s_pa_genes <- logfc_morph %>%
    filter(stage == "late_spermatocyte" & p_val_adj < 0.01 & avg_log2FC < 0) %>%
    pull("gene")

In [65]:
length(ec_eu_genes)
length(lc_eu_genes)
length(s_eu_genes)
length(ec_pa_genes)
length(lc_pa_genes)
length(s_pa_genes)

[1] 4377

[1] 4023

[1] 4023

[1] 5543

[1] 4531

[1] 4531

## Investigate mutant genes in single cell data set

### Look at expression patterns of the genes of interest

In [66]:
## identify the presence of mutant genes 
potential_interest %>%
    rename(gene = symbol) %>%
    left_join(logfc_morph, by = "gene")

   gene        position change   consequence              p_val
1  LOC6901779   645002  -/AGCCAC protein_altering_variant 1.355272e-42
2  LOC4815337   893839  G/C      stop_gained                        NA
3  LOC6902117  1625489  -/TGT    protein_altering_variant 5.042512e-18
4  LOC4815785  2706647  G/T      stop_gained              1.307539e-29
5  LOC4815774  2949241  C/T      stop_gained                        NA
6  LOC4815426  3468139  -/ACCAGT protein_altering_variant 5.583518e-21
7  LOC6902257  4221843  -/TGCTGC protein_altering_variant 1.209741e-81
8  LOC4815659  4250261  C/A      stop_gained              1.655317e-60
9  LOC26532021 4393675  T/G      stop_gained              1.043152e-15
10 LOC4814245  5602934  A/T      stop_gained                        NA
11 LOC4814348  6196915  C/A      stop_gained              2.038233e-68
   avg_log2FC pct.1 pct.2 p_val_adj    stage
1  -0.8570507 0.158 0.170 1.949017e-38 early_spermatocyte
2          NA    NA    NA           NA NA
3  -0.2748630 0.106 0.084 7.251636e-14 early_spermatocyte
4  -0.7183186 0.156 0.162 1.880372e-25 early_spermatocyte
5          NA    NA    NA           NA NA
6   0.1295619 0.068 0.038 8.029657e-17 late_spermatocyte
7   0.3858045 0.632 0.430 1.739729e-77 late_spermatocyte
8   0.2096326 0.360 0.229 2.380511e-56 early_spermatocyte
9   1.0007632 0.036 0.010 1.500156e-11 early_spermatocyte
10         NA    NA    NA           NA NA
11 -0.3965744 0.445 0.395 2.931182e-64 early_spermatocyte

### Look at expression pattern of differentially expressed genes for mutant

In [67]:
## add single cell data in annotated logfc
full_annotated_logfc <- annotated_logfc %>%
    mutate(Eusperm_Early_Spermatocytes = case_when(gene %in% ec_eu_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Eusperm_Late_Spermatocytes = case_when(gene %in% lc_eu_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Eusperm_Spermatids = case_when(gene %in% s_eu_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Parasperm_Early_Spermatocytes = case_when(gene %in% ec_pa_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Parasperm_Late_Spermatocytes = case_when(gene %in% lc_pa_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Parasperm_Spermatids = case_when(gene %in% s_pa_genes ~ "deg",
                                 TRUE ~ "not deg")) %>%
    rename(dpse = gene) %>%
    left_join(mel_ortho, by = "dpse") %>%
    unique() %>%
    rename(gene = dpse)
write_csv(full_annotated_logfc, "intermediate/full_annotated_logfc.csv")

In [68]:
## look for enrichment of downregulated genes for each stage
ec_eu_down_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hyper") %>%    
    select(gene, Eusperm_Early_Spermatocytes, direction) %>% unique() %>%
    group_by(Eusperm_Early_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Eusperm_Early_Spermatocytes") %>%
    rename(not_significant = 2)
ec_eu_down_chi <- ec_eu_down_df %>%
    as.matrix() %>%
    chisq.test()

ec_pa_down_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hyper") %>%    
    select(gene, Parasperm_Early_Spermatocytes, direction) %>% unique() %>%
    group_by(Parasperm_Early_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Parasperm_Early_Spermatocytes") %>%
    rename(not_significant = 2)
ec_pa_down_chi <- ec_pa_down_df %>%
    as.matrix() %>%
    chisq.test()

lc_eu_down_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hyper") %>%    
    select(gene, Eusperm_Late_Spermatocytes, direction) %>% unique() %>%
    group_by(Eusperm_Late_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Eusperm_Late_Spermatocytes") %>%
    rename(not_significant = 2)
lc_eu_down_chi <- lc_eu_down_df %>%
    as.matrix() %>%
    chisq.test()
    
lc_pa_down_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hyper") %>%    
    select(gene, Parasperm_Late_Spermatocytes, direction) %>% unique() %>%
    group_by(Parasperm_Late_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Parasperm_Late_Spermatocytes") %>%
    rename(not_significant = 2)
lc_pa_down_chi <- lc_pa_down_df %>%
    as.matrix() %>%
    chisq.test()

s_eu_down_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hyper") %>%    
    select(gene, Eusperm_Spermatids, direction) %>% unique() %>%
    group_by(Eusperm_Spermatids, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Eusperm_Spermatids") %>%
    rename(not_significant = 2)
s_eu_down_chi <- s_eu_down_df %>%
    as.matrix() %>%
    chisq.test()

s_pa_down_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hyper") %>%    
    select(gene, Parasperm_Spermatids, direction) %>% unique() %>%
    group_by(Parasperm_Spermatids, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Parasperm_Spermatids") %>%
    rename(not_significant = 2)
s_pa_down_chi <- s_pa_down_df %>%
    as.matrix() %>%
    chisq.test()

## look for enrichment of upregulated genes for each stage
ec_eu_up_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hypo") %>%    
    select(gene, Eusperm_Early_Spermatocytes, direction) %>% unique() %>%
    group_by(Eusperm_Early_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Eusperm_Early_Spermatocytes") %>%
    rename(not_significant = 2)
ec_eu_up_chi <- ec_eu_up_df %>%
    as.matrix() %>%
    chisq.test()

ec_pa_up_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hypo") %>%    
    select(gene, Parasperm_Early_Spermatocytes, direction) %>% unique() %>%
    group_by(Parasperm_Early_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Parasperm_Early_Spermatocytes") %>%
    rename(not_significant = 2)
ec_pa_up_chi <- ec_pa_up_df %>%
    as.matrix() %>%
    chisq.test()

lc_eu_up_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hypo") %>%    
    select(gene, Eusperm_Late_Spermatocytes, direction) %>% unique() %>%
    group_by(Eusperm_Late_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Eusperm_Late_Spermatocytes") %>%
    rename(not_significant = 2)
lc_eu_up_chi <- lc_eu_up_df %>%
    as.matrix() %>%
    chisq.test()

lc_pa_up_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hypo") %>%    
    select(gene, Parasperm_Late_Spermatocytes, direction) %>% unique() %>%
    group_by(Parasperm_Late_Spermatocytes, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Parasperm_Late_Spermatocytes") %>%
    rename(not_significant = 2)
lc_pa_up_chi <- lc_pa_up_df %>%
    as.matrix() %>%
    chisq.test()

s_eu_up_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hypo") %>%    
    select(gene, Eusperm_Spermatids, direction) %>% unique() %>%
    group_by(Eusperm_Spermatids, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Eusperm_Spermatids") %>%
    rename(not_significant = 2)
s_eu_up_chi <- s_eu_up_df %>%
    as.matrix() %>%
    chisq.test()

s_pa_up_df <- full_annotated_logfc %>%
    filter(comparison == "sex ratio_mutant" & direction != "hypo") %>%    
    select(gene, Parasperm_Spermatids, direction) %>% unique() %>%
    group_by(Parasperm_Spermatids, direction) %>%
    count() %>%
    pivot_wider(names_from = direction, values_from = n) %>%
    column_to_rownames("Parasperm_Spermatids") %>%
    rename(not_significant = 2)
s_pa_up_chi <- s_pa_up_df %>%
    as.matrix() %>%
    chisq.test()

In [69]:
## create data frame of enrichment
morph_mutant_enrichment <- data.frame(stage = c("early_eusperm", "early_eusperm", "early_parasperm", "early_parasperm", 
                                                "late_eusperm", "late_eusperm", "late_parasperm", "late_parasperm", 
                                                "eusperm_spermatids", "eusperm_spermatids", "parasperm_spermatids", "parasperm_spermatids"),
                                      direction = rep(c("down", "up"), times = 6),
                                      pvalue = c(ec_eu_down_chi$p.value, ec_eu_up_chi$p.value, ec_pa_down_chi$p.value, ec_pa_up_chi$p.value,
                                                 lc_eu_down_chi$p.value, lc_eu_up_chi$p.value, lc_pa_down_chi$p.value, lc_pa_up_chi$p.value,
                                                 s_eu_down_chi$p.value, s_eu_up_chi$p.value, s_pa_down_chi$p.value, s_pa_up_chi$p.value),
                                      deg_ratio = c(ec_eu_down_df["deg", "hypo"]/ec_eu_down_df["deg", "not_significant"], ec_eu_up_df["deg", "hyper"]/ec_eu_up_df["deg", "not_significant"],
                                                    ec_pa_down_df["deg", "hypo"]/ec_pa_down_df["deg", "not_significant"], ec_pa_up_df["deg", "hyper"]/ec_pa_up_df["deg", "not_significant"],
                                                    lc_eu_down_df["deg", "hypo"]/lc_eu_down_df["deg", "not_significant"], lc_eu_up_df["deg", "hyper"]/lc_eu_up_df["deg", "not_significant"],
                                                    lc_pa_down_df["deg", "hypo"]/lc_pa_down_df["deg", "not_significant"], lc_pa_up_df["deg", "hyper"]/lc_pa_up_df["deg", "not_significant"],
                                                    s_eu_down_df["deg", "hypo"]/s_eu_down_df["deg", "not_significant"], s_eu_up_df["deg", "hyper"]/s_eu_up_df["deg", "not_significant"],
                                                    s_pa_down_df["deg", "hypo"]/s_pa_down_df["deg", "not_significant"], s_pa_up_df["deg", "hyper"]/s_pa_up_df["deg", "not_significant"]),
                                      notdeg_ratio = c(ec_eu_down_df["not deg", "hypo"]/ec_eu_down_df["not deg", "not_significant"], ec_eu_up_df["not deg", "hyper"]/ec_eu_up_df["not deg", "not_significant"],
                                                    ec_pa_down_df["not deg", "hypo"]/ec_pa_down_df["not deg", "not_significant"], ec_pa_up_df["not deg", "hyper"]/ec_pa_up_df["not deg", "not_significant"],
                                                    lc_eu_down_df["not deg", "hypo"]/lc_eu_down_df["not deg", "not_significant"], lc_eu_up_df["not deg", "hyper"]/lc_eu_up_df["not deg", "not_significant"],
                                                    lc_pa_down_df["not deg", "hypo"]/lc_pa_down_df["not deg", "not_significant"], lc_pa_up_df["not deg", "hyper"]/lc_pa_up_df["not deg", "not_significant"],
                                                    s_eu_down_df["not deg", "hypo"]/s_eu_down_df["not deg", "not_significant"], s_eu_up_df["not deg", "hyper"]/s_eu_up_df["not deg", "not_significant"],
                                                    s_pa_down_df["not deg", "hypo"]/s_pa_down_df["not deg", "not_significant"], s_pa_up_df["not deg", "hyper"]/s_pa_up_df["not deg", "not_significant"]))
## perform multiple testing correction
morph_mutant_enrichment$adjusted_p <- p.adjust(morph_mutant_enrichment$pvalue, method = "BH")

## interpret results of chi squared test
morph_mutant_enrichment %>%
    mutate(enrichment = case_when(adjusted_p < 0.01 & deg_ratio > notdeg_ratio ~ "over represented in stage",
                                  adjusted_p < 0.01 & deg_ratio < notdeg_ratio ~ "under represented in stage",
                                  TRUE ~ "not significant"))

   stage                direction pvalue       deg_ratio notdeg_ratio
1  early_eusperm        down      9.965923e-06 0.7500000 0.5507442
2  early_eusperm        up        2.301646e-04 0.4587500 0.6082544
3  early_parasperm      down      7.159107e-06 0.5173745 0.7069243
4  early_parasperm      up        6.624595e-04 0.6293436 0.4943639
5  late_eusperm         down      1.221893e-02 0.3925234 0.6319668
6  late_eusperm         up        4.198307e-01 0.6355140 0.5518194
7  late_parasperm       down      7.770967e-04 0.8833333 0.5981888
8  late_parasperm       up        1.785990e-07 0.2388889 0.5829361
9  eusperm_spermatids   down      1.221893e-02 0.3925234 0.6319668
10 eusperm_spermatids   up        4.198307e-01 0.6355140 0.5518194
11 parasperm_spermatids down      7.770967e-04 0.8833333 0.5981888
12 parasperm_spermatids up        1.785990e-07 0.2388889 0.5829361
   adjusted_p   enrichment
1  2.989777e-05 over represented in stage
2  5.523951e-04 under represented in stage
3  2.863643e-05 under represented in stage
4  1.165645e-03 over represented in stage
5  1.466272e-02 not significant
6  4.198307e-01 not significant
7  1.165645e-03 over represented in stage
8  1.071594e-06 under represented in stage
9  1.466272e-02 not significant
10 4.198307e-01 not significant
11 1.165645e-03 over represented in stage
12 1.071594e-06 under represented in stage

### Look at expression pattern of branch associated genes

In [70]:
## look for enrichment of downregulated genes for each stage
ec_eu_branch_df <- full_annotated_logfc %>%
    select(gene, Eusperm_Early_Spermatocytes, credible) %>% unique() %>%
    group_by(Eusperm_Early_Spermatocytes, credible) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("Eusperm_Early_Spermatocytes")
ec_eu_branch_chi <- ec_eu_branch_df %>%
    as.matrix() %>%
    chisq.test()

ec_pa_branch_df <- full_annotated_logfc %>%
    select(gene, Parasperm_Early_Spermatocytes, credible) %>% unique() %>%
    group_by(Parasperm_Early_Spermatocytes, credible) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("Parasperm_Early_Spermatocytes")
ec_pa_branch_chi <- ec_pa_branch_df %>%
    as.matrix() %>%
    chisq.test()

lc_eu_branch_df <- full_annotated_logfc %>% 
    select(gene, Eusperm_Late_Spermatocytes, credible) %>% unique() %>%
    group_by(Eusperm_Late_Spermatocytes, credible) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("Eusperm_Late_Spermatocytes")
lc_eu_branch_chi <- lc_eu_branch_df %>%
    as.matrix() %>%
    chisq.test()
    
lc_pa_branch_df <- full_annotated_logfc %>% 
    select(gene, Parasperm_Late_Spermatocytes, credible) %>% unique() %>%
    group_by(Parasperm_Late_Spermatocytes, credible) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("Parasperm_Late_Spermatocytes")
lc_pa_branch_chi <- lc_pa_branch_df %>%
    as.matrix() %>%
    chisq.test()

s_eu_branch_df <- full_annotated_logfc %>%
    select(gene, Eusperm_Spermatids, credible) %>% unique() %>%
    group_by(Eusperm_Spermatids, credible) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("Eusperm_Spermatids")
s_eu_branch_chi <- s_eu_branch_df %>%
    as.matrix() %>%
    chisq.test()

s_pa_branch_df <- full_annotated_logfc %>%
    select(gene, Parasperm_Spermatids, credible) %>% unique() %>%
    group_by(Parasperm_Spermatids, credible) %>%
    count() %>%
    pivot_wider(names_from = credible, values_from = n) %>%
    column_to_rownames("Parasperm_Spermatids")
s_pa_branch_chi <- s_pa_branch_df %>%
    as.matrix() %>%
    chisq.test()

In [71]:
## create data frame of enrichment
morph_branch_enrichment <- data.frame(stage = c("early_eusperm", "early_parasperm", "late_eusperm", "late_parasperm", "eusperm_spermatids", "parasperm_spermatids"),
                                      pvalue = c(ec_eu_branch_chi$p.value, ec_pa_branch_chi$p.value,
                                                 lc_eu_branch_chi$p.value, lc_pa_branch_chi$p.value,
                                                 s_eu_branch_chi$p.value, s_pa_branch_chi$p.value),
                                      deg_ratio = c(ec_eu_branch_df["deg", "credible"]/ec_eu_branch_df["deg", "non-credible"], ec_pa_branch_df["deg", "credible"]/ec_pa_branch_df["deg", "non-credible"],
                                                    lc_eu_branch_df["deg", "credible"]/lc_eu_branch_df["deg", "non-credible"], lc_pa_branch_df["deg", "credible"]/lc_pa_branch_df["deg", "non-credible"],
                                                    s_eu_branch_df["deg", "credible"]/s_eu_branch_df["deg", "non-credible"], s_pa_branch_df["deg", "credible"]/s_pa_branch_df["deg", "non-credible"]),
                                      notdeg_ratio = c(ec_eu_branch_df["not deg", "credible"]/ec_eu_branch_df["not deg", "non-credible"], ec_pa_branch_df["not deg", "credible"]/ec_pa_branch_df["not deg", "non-credible"],
                                                    lc_eu_branch_df["not deg", "credible"]/lc_eu_branch_df["not deg", "non-credible"], lc_pa_branch_df["not deg", "credible"]/lc_pa_branch_df["not deg", "non-credible"],
                                                    s_eu_branch_df["not deg", "credible"]/s_eu_branch_df["not deg", "non-credible"], s_pa_branch_df["not deg", "credible"]/s_pa_branch_df["not deg", "non-credible"]))
## perform multiple testing correction
morph_branch_enrichment$adjusted_p <- p.adjust(morph_branch_enrichment$pvalue, method = "BH")

## interpret results of chi squared test
morph_branch_enrichment %>%
    mutate(enrichment = case_when(adjusted_p < 0.01 & deg_ratio > notdeg_ratio ~ "over represented in stage",
                                  adjusted_p < 0.01 & deg_ratio < notdeg_ratio ~ "under represented in stage",
                                  TRUE ~ "not significant"))

  stage                pvalue       deg_ratio  notdeg_ratio adjusted_p
1 early_eusperm        2.509364e-09 0.11202014 0.05802387   1.505618e-08
2 early_parasperm      1.123793e-06 0.05402844 0.09579158   3.371380e-06
3 late_eusperm         5.986044e-01 0.06372549 0.07725517   6.334920e-01
4 late_parasperm       6.334920e-01 0.08522727 0.07594639   6.334920e-01
5 eusperm_spermatids   5.986044e-01 0.06372549 0.07725517   6.334920e-01
6 parasperm_spermatids 6.334920e-01 0.08522727 0.07594639   6.334920e-01
  enrichment
1 over represented in stage
2 under represented in stage
3 not significant
4 not significant
5 not significant
6 not significant

In [72]:
## get the list of genes whose increase in expression is associated with an increase in parasperm content
positive_branch_genes <- credible_df %>%
    filter(sign > 0) %>%
    pull(transcript_id)

## determine what these positive branch genes are doing in the single cell data
logfc_morph %>%
    filter(gene %in% positive_branch_genes & p_val_adj < 0.01) %>%
    mutate(direction = case_when(avg_log2FC < 0 ~ "eusperm",
                                 avg_log2FC > 0 ~ "parasperm")) %>%
    group_by(stage, direction) %>%
    count()

  stage              direction n
1 early_spermatocyte eusperm   4
2 early_spermatocyte parasperm 6
3 late_spermatocyte  eusperm   2

In [121]:
logfc_morph %>%
    filter(gene %in% positive_branch_genes & p_val_adj < 0.01) %>%
    mutate(direction = case_when(avg_log2FC < 0 ~ "eusperm",
                                 avg_log2FC > 0 ~ "parasperm"))

   gene       p_val        avg_log2FC pct.1 pct.2 p_val_adj
1  LOC6897142 0.000000e+00  2.1381177 0.991 0.789 0.000000e+00
2  LOC6897697 0.000000e+00  1.3177060 0.974 0.802 0.000000e+00
3  LOC4818038 0.000000e+00  0.7866458 0.985 0.886 0.000000e+00
4  LOC4803583 0.000000e+00  2.2592401 1.000 0.982 0.000000e+00
5  LOC4818032 2.527760e-70  0.3207878 0.965 0.888 3.635172e-66
6  LOC4803901 4.662660e-58 -0.2823437 0.997 0.997 6.705371e-54
7  LOC6897264 1.149386e-54 -0.2460309 0.999 1.000 1.652932e-50
8  LOC6902046 1.027001e-38  0.1807452 0.967 0.917 1.476930e-34
9  LOC4818036 5.779565e-13 -0.1245023 0.955 0.948 8.311592e-09
10 LOC4813023 1.610469e-11 -0.1681082 0.989 0.970 2.316015e-07
11 LOC6898105 7.166095e-96 -0.4015163 0.834 0.802 1.030556e-91
12 LOC6898499 5.157274e-71 -0.3389846 0.986 0.991 7.416676e-67
   stage              direction
1  early_spermatocyte parasperm
2  early_spermatocyte parasperm
3  early_spermatocyte parasperm
4  early_spermatocyte parasperm
5  early_spermatocyte parasperm
6  early_spermatocyte eusperm
7  early_spermatocyte eusperm
8  early_spermatocyte parasperm
9  early_spermatocyte eusperm
10 early_spermatocyte eusperm
11 late_spermatocyte  eusperm
12 late_spermatocyte  eusperm

## Characterize Genes of Interest

In [75]:
## get the genes with the interesting mutations
potential_genes <- potential_interest %>%
    pull("symbol")

annotated_logfc %>%
    filter(gene %in% potential_genes) %>%
    rename(symbol = gene) %>%
    select(symbol, direction) %>%
    right_join(potential_interest, by = "symbol") %>%
    mutate(Eusperm_Early_Spermatocytes = case_when(symbol %in% ec_eu_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Eusperm_Late_Spermatocytes = case_when(symbol %in% lc_eu_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Eusperm_Spermatids = case_when(symbol %in% s_eu_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Parasperm_Early_Spermatocytes = case_when(symbol %in% ec_pa_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Parasperm_Late_Spermatocytes = case_when(symbol %in% lc_pa_genes ~ "deg",
                                 TRUE ~ "not deg"),
           Parasperm_Spermatids = case_when(symbol %in% s_pa_genes ~ "deg",
                                 TRUE ~ "not deg"),
           credible = case_when(symbol %in% credible_down_genes ~ "credible"),
           testes = case_when(symbol %in% testes_genes ~ "testes")) %>%
    rename(dpse = symbol) %>%
    left_join(mel_ortho, by = "dpse") %>%
    unique()

   dpse        direction       position change   consequence
1  LOC4814348  not significant 6196915  C/A      stop_gained
2  LOC4814348  not significant 6196915  C/A      stop_gained
3  LOC6901779  hyper            645002  -/AGCCAC protein_altering_variant
4  LOC6902257  hyper           4221843  -/TGCTGC protein_altering_variant
5  LOC4815337  NA               893839  G/C      stop_gained
6  LOC6902117  NA              1625489  -/TGT    protein_altering_variant
7  LOC4815785  NA              2706647  G/T      stop_gained
8  LOC4815774  NA              2949241  C/T      stop_gained
9  LOC4815426  NA              3468139  -/ACCAGT protein_altering_variant
10 LOC4815659  NA              4250261  C/A      stop_gained
11 LOC26532021 NA              4393675  T/G      stop_gained
12 LOC4814245  NA              5602934  A/T      stop_gained
   Eusperm_Early_Spermatocytes Eusperm_Late_Spermatocytes Eusperm_Spermatids
1  not deg                     not deg                    not deg
2  not deg                     not deg                    not deg
3  not deg                     not deg                    not deg
4  not deg                     deg                        deg
5  not deg                     not deg                    not deg
6  not deg                     not deg                    not deg
7  not deg                     not deg                    not deg
8  not deg                     not deg                    not deg
9  not deg                     deg                        deg
10 deg                         not deg                    not deg
11 deg                         not deg                    not deg
12 not deg                     not deg                    not deg
   Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
1  deg                           not deg
2  deg                           not deg
3  deg                           not deg
4  not deg                       not deg
5  not deg                       not deg
6  deg                           not deg
7  deg                           not deg
8  not deg                       not deg
9  not deg                       not deg
10 not deg                       not deg
11 not deg                       not deg
12 not deg                       not deg
   Parasperm_Spermatids credible testes dmel        paralog score
1  not deg              NA       NA     CG18259     1:m        NA
2  not deg              NA       NA     CG6961      1:m     30805
3  not deg              NA       NA     CHES-1-like 1:1     12587
4  not deg              NA       NA     HUWE1       1:1     12248
5  not deg              NA       NA     Nek2        1:1     25920
6  not deg              NA       NA     CG14200     1:1     12375
7  not deg              NA       NA     C3G         1:1     25901
8  not deg              NA       NA     CG9673      1:1     14705
9  not deg              NA       NA     Met         1:1     12860
10 not deg              NA       NA     CG8134      1:1     19508
11 not deg              NA       NA     NA          NA         NA
12 not deg              NA       NA     CG15312     1:1     19192

## Investigate specific genes that would be of interest based on previous literature

### Set up Data

In [76]:
## load in orthologs between D. melanogaster and D. pseudoobscura
mel_ortho <- read_delim("../workflow/trinotate/drosoma_pse_mel.txt", col_names = FALSE)
names(mel_ortho) <- c("dpse", "dmel", "paralog", "score")

Rows: 13772 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): X1, X2, X3
dbl (1): X4

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [100]:
## load in teh list of SFPs from Wigby et al. 2020
wigby_sfp <- read_csv("input/wigby_2020_sfp_list.csv", skip = 1) %>%
    janitor::clean_names()

Rows: 713 Columns: 29
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (27): Name, Symbol, CG#, FBgn#, Cytogenetic map, Chromosome, Strand, Pro...
dbl  (2): Location Max, Location Min

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Search data for specific genes

In [119]:
## identify D. pseudoobscura paralogs
test <- wigby_sfp %>%
    rename(dmel = symbol) %>%
    inner_join(mel_ortho, by = "dmel", relationship = "many-to-many") %>%
    select(name, dpse, chromosome) %>%
    rename(gene = dpse)

## determine if SFPs appear in our data set as differentially expressed are associated with parasperm
annotated_sfp <- full_annotated_logfc %>%
    inner_join(test, by = "gene", relationship = "many-to-many") %>%
    filter(comparison == "sex ratio_mutant")

annotated_sfp %>%
    select(gene, direction) %>% unique() %>%
    group_by(direction) %>%
    count()
annotated_sfp %>%
    select(gene, credible) %>% unique() %>%
    group_by(credible) %>%
    count()

  direction       n
1 hyper           21
2 hypo             8
3 not significant 18

  credible     n
1 non-credible 47

In [135]:
annotated_sfp_trunc <- annotated_sfp %>%
    select(gene, dmel, name, logfc, pvalue) %>%
    left_join(tau, by = "gene") %>%
    mutate(early_spermatocyte = case_when(gene %in% ec_eu_genes ~ "eusperm",
                                          gene %in% ec_pa_genes ~ "parasperm",
                                          TRUE ~ "not_deg"),
           late_spermatocyte = case_when(gene %in% lc_eu_genes ~ "eusperm",
                                         gene %in% lc_pa_genes ~ "parasperm",
                                         TRUE ~ "not_deg"),
           spermatid = case_when(gene %in% s_eu_genes ~ "eusperm",
                                 gene %in% s_pa_genes ~ "parasperm",
                                 TRUE ~ "not_deg")) %>%
    select(gene, dmel, logfc, pvalue, tau, tau_tissue, early_spermatocyte, late_spermatocyte, spermatid) %>%
    rename(dpse_name = gene, dmel_name = dmel) %>%
    unique()
# write_csv(annotated_sfp_trunc, "intermediate/pseudoobscura_heteromorphism_sfp.csv")

In [115]:
## get the list of D. pseudoobscura orthologs of SFPs in our dataset
dpse_sfp <- unique(annotated_sfp$gene)

length(dpse_sfp)
length(dpse_sfp[dpse_sfp %in% ec_eu_genes])
length(dpse_sfp[dpse_sfp %in% lc_eu_genes])
length(dpse_sfp[dpse_sfp %in% s_eu_genes])
length(dpse_sfp[dpse_sfp %in% ec_pa_genes])
length(dpse_sfp[dpse_sfp %in% lc_pa_genes])
length(dpse_sfp[dpse_sfp %in% s_pa_genes])

[1] 47

[1] 17

[1] 1

[1] 1

[1] 18

[1] 3

[1] 3

In [120]:
## determine if any sperm proteins are in the data set
full_annotated_logfc %>%
    rename(symbol = gene) %>%
    inner_join(sperm_dpse, by = "symbol") %>%
    filter(comparison == "sex ratio_mutant")

   symbol      ...1  comparison       logfc       pvalue       significance
1  LOC4817494  17783 sex ratio_mutant  0.03738714 9.998863e-01 not significant
2  LOC4817554  17918 sex ratio_mutant -0.34200737 6.013668e-03 significant
3  LOC6901019  18869 sex ratio_mutant  1.62654994 4.745812e-05 significant
4  LOC4814222  19001 sex ratio_mutant  1.75668576 2.190587e-04 significant
5  LOC26532861  6593 sex ratio_mutant -0.50714680 7.927122e-05 significant
6  LOC26532861  6593 sex ratio_mutant -0.50714680 7.927122e-05 significant
7  LOC26532861  6593 sex ratio_mutant -0.50714680 7.927122e-05 significant
8  LOC4803148   6605 sex ratio_mutant  1.01286730 8.833909e-09 significant
9  LOC4803148   6605 sex ratio_mutant  1.01286730 8.833909e-09 significant
10 LOC4803148   6605 sex ratio_mutant  1.01286730 8.833909e-09 significant
   direction       color                               credible
1  not significant not significant                     non-credible
2  hypo            marginally differentially expressed non-credible
3  hyper           marginally differentially expressed non-credible
4  hyper           marginally differentially expressed non-credible
5  hypo            marginally differentially expressed non-credible
6  hypo            marginally differentially expressed non-credible
7  hypo            marginally differentially expressed non-credible
8  hyper           marginally differentially expressed non-credible
9  hyper           marginally differentially expressed non-credible
10 hyper           marginally differentially expressed non-credible
   testes_specificity ⋯ Eusperm_Early_Spermatocytes Eusperm_Late_Spermatocytes
1  other              ⋯ not deg                     not deg
2  other              ⋯ deg                         not deg
3  other              ⋯ not deg                     not deg
4  other              ⋯ deg                         not deg
5  testes             ⋯ not deg                     not deg
6  testes             ⋯ not deg                     not deg
7  testes             ⋯ not deg                     not deg
8  testes             ⋯ not deg                     not deg
9  testes             ⋯ not deg                     not deg
10 testes             ⋯ not deg                     not deg
   Eusperm_Spermatids Parasperm_Early_Spermatocytes
1  not deg            deg
2  not deg            not deg
3  not deg            not deg
4  not deg            not deg
5  not deg            deg
6  not deg            deg
7  not deg            deg
8  not deg            deg
9  not deg            deg
10 not deg            deg
   Parasperm_Late_Spermatocytes Parasperm_Spermatids dmel   paralog score
1  not deg                      not deg              Idgf3  1:1      5717
2  not deg                      not deg              Pde1c  1:1      5446
3  not deg                      not deg              Tsf1   1:1     19710
4  not deg                      not deg              Idgf4  1:1     19197
5  not deg                      not deg              scpr-C n:m     32268
6  not deg                      not deg              scpr-B n:m        NA
7  not deg                      not deg              scpr-A n:m        NA
8  not deg                      not deg              scpr-C n:m        NA
9  not deg                      not deg              scpr-B n:m        NA
10 not deg                      not deg              scpr-A n:m     32249
   sperm_protein
1  Idgf3
2  Phosphodiesterase 1c
3  Transferrin 1
4  Imaginal disc growth factor 4
5  SCP-containing protein C
6  SCP-containing protein C
7  SCP-containing protein C
8  SCP-containing protein C
9  SCP-containing protein C
10 SCP-containing protein C

In [140]:
mel_ortho %>%
    filter(dmel == "vis" | dmel == "CROL" | dmel == "Caup" ) %>%
    rename(gene = dpse) %>%
    left_join(full_annotated_logfc, by = "gene")

  gene       dmel.x paralog.x score.x ...1  comparison       logfc
1 LOC4805467 vis    1:m       NA      11834 sex ratio_mutant 0.2575892
2 LOC4805467 vis    1:m       NA      11834 sex ratio_mutant 0.2575892
  pvalue    significance    direction       ⋯ x     Eusperm_Early_Spermatocytes
1 0.3066086 not significant not significant ⋯ other deg
2 0.3066086 not significant not significant ⋯ other deg
  Eusperm_Late_Spermatocytes Eusperm_Spermatids Parasperm_Early_Spermatocytes
1 not deg                    not deg            not deg
2 not deg                    not deg            not deg
  Parasperm_Late_Spermatocytes Parasperm_Spermatids dmel.y paralog.y score.y
1 not deg                      not deg              vis    1:m         NA
2 not deg                      not deg              achi   1:m       6728

In [90]:
## nebenkern formation
## fzo (fuzzy onion) - not found (first gene related to mitochondria, cannot aggregate)
## Larp - not found (partitions mitochondria into nebenkern)
## Pink1 (LOC4815974) - not differential (maintains separation)
## Parkin - not found (maintains separation) -> tried park (uniprot), not differential
test <- mel_ortho %>%
    filter(dmel == "park") %>%
    pull("dpse")
full_annotated_logfc %>%
    filter(gene %in% test)

  gene       ...1  comparison       logfc      pvalue    significance
1 LOC4812935 26105 sex ratio_mutant -0.2605455 0.2726715 not significant
  direction       color           credible     testes_specificity x
1 not significant not significant non-credible other              other
  Eusperm_Early_Spermatocytes Eusperm_Late_Spermatocytes Eusperm_Spermatids
1 deg                         not deg                    not deg
  Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
1 not deg                       not deg
  Parasperm_Spermatids dmel paralog score
1 not deg              park 1:1     20550

In [91]:
## nebenkern unfurling
## Milton - not found (anchors nebernkern to nuclei and allows sliding of microtubules) -> tried milt (uniprot), not significant
## Lis-1 (LOC4803869) - not differential (anchors nebenkern to nuclei)
## Miro (LOC4801756) - not differential (allows sliding of cytosolic microtubules)
## Nebbish - not found (elongation is truncated) -> tried neb (uniprot), not significant
## Khc73 - not found (elongation is truncated) -> tried Khc-73 (uniprot), significant
## fascetto - not found (elongation is truncated)  -> tried feo (uniprot), significant
## nmd (LOC117183914) - not differential (decreased number of mitochondria)
## cnn (LOC4804379) - not differential (required for assembly of flagellar axoneme)
## Grip members - 3/7 differentially expressed (localize to basal body for microtubule formation)
test <- mel_ortho %>%
    filter(dmel == "feo") %>%
    pull("dpse")
full_annotated_logfc %>%
    filter(gene %in% test)

     gene ...1 comparison logfc pvalue significance direction color credible
     testes_specificity x Eusperm_Early_Spermatocytes
     Eusperm_Late_Spermatocytes Eusperm_Spermatids
     Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
     Parasperm_Spermatids dmel paralog score

In [92]:
## mitochondrial energetics
## Mic26-27 - not found (part of cristae organizing system)
## QIL1 (LOC4812916) - not differential (part of cristae organizing system)
## Mitofilin (LOC6896986) - not differential (part of cristae organizing system)
## Chchd3 (LOC4800334) - not differential (part of cristae organizing system)
## knon (LOC4803786) - not differential (electron transportation)
## knon (LOC4803786) - not differential (electron transportation)
## blw (LOC4803853) - differential (electron transportation)
test <- mel_ortho %>%
    filter(dmel == "Mic26-27") %>%
    pull("dpse")
full_annotated_logfc %>%
    filter(gene %in% test)

     gene ...1 comparison logfc pvalue significance direction color credible
     testes_specificity x Eusperm_Early_Spermatocytes
     Eusperm_Late_Spermatocytes Eusperm_Spermatids
     Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
     Parasperm_Spermatids dmel paralog score

In [82]:
## list of genes with differential expression
mito_genes <- c("Khc-73", "feo", "blw")
mel_ortho %>%
    filter(dmel %in% mito_genes | grepl("Grip", dmel)) %>%
    select(dpse, dmel) %>%
    rename(gene = dpse) %>%
    left_join(annotated_logfc, by = "gene") %>%
    select(-c(pvalue, direction, color))

   gene       dmel    ...1  comparison       logfc      significance
1  LOC4803853 blw      8243 sex ratio_mutant  0.4075890 significant
2  LOC4804863 Khc-73  10481 sex ratio_mutant  0.4705689 significant
3  LOC6899804 Grip75     NA NA                       NA NA
4  LOC4817648 Grip71     NA NA                       NA NA
5  LOC6902241 feo        NA NA                       NA NA
6  LOC4815237 Grip84     NA NA                       NA NA
7  LOC4815390 Grip       NA NA                       NA NA
8  LOC4815196 Grip91  22097 sex ratio_mutant -0.1469523 not significant
9  LOC6901874 Grip128    NA NA                       NA NA
10 LOC4815480 feo        NA NA                       NA NA
11 LOC4813265 Grip163    NA NA                       NA NA
   credible     testes_specificity x
1  non-credible other              other
2  non-credible other              other
3  NA           NA                 NA
4  NA           NA                 NA
5  NA           NA                 NA
6  NA           NA                 NA
7  NA           NA                 NA
8  non-credible other              other
9  NA           NA                 NA
10 NA           NA                 NA
11 NA           NA                 NA

In [93]:
## acrosome genes
## Four way stop (fws) - not differential (golgi and endosomal trafficking regulators)
## Giotto (Gio) - not found (golgi and endosomal trafficking regulators)
## Rab11 - not differential (golgi and endosomal trafficking regulators)
## Nuclear fallout (nuf) - not differential (Rab11 effector Nuclear fallout)
## Brunelleschi (brun) - differential (golgi and endosomal trafficking regulators)
## Lectin Wheat Germ Agglutinin (WGA) - not found (secretory trafficking)
## Sneaky (snky) - differential (sperm plasma membrane breakdown during fertilization)
## Misfire (mfr) - differential (sperm plasma membrane breakdown)
test <- mel_ortho %>%
    filter(dmel == "mfr") %>%
    pull("dpse")
full_annotated_logfc %>%
    filter(gene %in% test)

     gene ...1 comparison logfc pvalue significance direction color credible
     testes_specificity x Eusperm_Early_Spermatocytes
     Eusperm_Late_Spermatocytes Eusperm_Spermatids
     Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
     Parasperm_Spermatids dmel paralog score

In [94]:
## golgi apparatus genes
## Golgins lava lamp (Lva) - differential
## GCC88 - not differential
## GM130 - not differential
## Golgi alpha-mannosidase II (GMII) - not found; (alpha-Man-IIa) - differential
## Golgi phosphoprotein-3 (GOLPHh3) - not found; (sau) - not differential
## Coatomer (COP I) - not found; (gammaCOP) - not significant
## Gga - not differential (clathrin adaptors)
## AP-1 - not found (clathrin adaptors)
test <- mel_ortho %>%
    filter(dmel == "AP-1") %>%
    pull("dpse")
full_annotated_logfc %>%
    filter(gene %in% test)

     gene ...1 comparison logfc pvalue significance direction color credible
     testes_specificity x Eusperm_Early_Spermatocytes
     Eusperm_Late_Spermatocytes Eusperm_Spermatids
     Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
     Parasperm_Spermatids dmel paralog score

In [95]:
## search for aquaporins
test <- mel_ortho %>%
    filter(grepl("AQP", dmel)) %>%
    pull("dpse")
full_annotated_logfc %>%
    filter(gene %in% test)

     gene ...1 comparison logfc pvalue significance direction color credible
     testes_specificity x Eusperm_Early_Spermatocytes
     Eusperm_Late_Spermatocytes Eusperm_Spermatids
     Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
     Parasperm_Spermatids dmel paralog score

In [97]:
## Odarant binding genes (Obp) - (odarant binding genes essential to male fertility)
test <- mel_ortho %>%
    filter(dmel == "lush") %>%
    pull("dpse")
full_annotated_logfc %>%
    filter(gene %in% test)
test <- mel_ortho %>%
    filter(grepl("Obp", dmel)) %>%
    rename(gene = dpse)
full_annotated_logfc %>%
    right_join(test, by = "gene")

     gene ...1 comparison logfc pvalue significance direction color credible
     testes_specificity x Eusperm_Early_Spermatocytes
     Eusperm_Late_Spermatocytes Eusperm_Spermatids
     Parasperm_Early_Spermatocytes Parasperm_Late_Spermatocytes
     Parasperm_Spermatids dmel paralog score

   gene        ...1 comparison       logfc       pvalue       significance
1  LOC4804338  9341 sex ratio_mutant -0.79341126 5.597574e-09 significant
2  LOC6898273  8300 sex ratio_mutant  0.06703936 9.977918e-01 not significant
3  LOC4800495   566 sex ratio_mutant -0.26816585 2.086075e-01 not significant
4  LOC4800502    NA NA                        NA           NA NA
5  LOC4800501    NA NA                        NA           NA NA
6  LOC6896778    NA NA                        NA           NA NA
7  LOC4801915    NA NA                        NA           NA NA
8  LOC4801921    NA NA                        NA           NA NA
9  LOC4801922    NA NA                        NA           NA NA
10 LOC4802242    NA NA                        NA           NA NA
11 LOC26532407   NA NA                        NA           NA NA
12 LOC4802940    NA NA                        NA           NA NA
13 LOC4803841    NA NA                        NA           NA NA
14 LOC4803842    NA NA                        NA           NA NA
15 LOC4803843    NA NA                        NA           NA NA
16 LOC4803844    NA NA                        NA           NA NA
17 LOC4803885    NA NA                        NA           NA NA
18 LOC4803886    NA NA                        NA           NA NA
19 LOC4803887    NA NA                        NA           NA NA
20 LOC4803889    NA NA                        NA           NA NA
21 LOC4804234    NA NA                        NA           NA NA
22 LOC4804632    NA NA                        NA           NA NA
23 LOC4804642    NA NA                        NA           NA NA
24 LOC6898639    NA NA                        NA           NA NA
25 LOC4804957    NA NA                        NA           NA NA
26 LOC4804958    NA NA                        NA           NA NA
27 LOC6898716    NA NA                        NA           NA NA
28 LOC4804960    NA NA                        NA           NA NA
29 LOC4804962    NA NA                        NA           NA NA
30 LOC4804965    NA NA                        NA           NA NA
31 LOC4804966    NA NA                        NA           NA NA
32 LOC4805094    NA NA                        NA           NA NA
33 LOC4805657    NA NA                        NA           NA NA
34 LOC4818071    NA NA                        NA           NA NA
35 LOC4815875    NA NA                        NA           NA NA
36 LOC4815452    NA NA                        NA           NA NA
37 LOC4815713    NA NA                        NA           NA NA
38 LOC4816057    NA NA                        NA           NA NA
39 LOC4816056    NA NA                        NA           NA NA
40 LOC4812865    NA NA                        NA           NA NA
41 LOC6900159    NA NA                        NA           NA NA
   direction       color                               credible
1  hypo            marginally differentially expressed non-credible
2  not significant not significant                     non-credible
3  not significant not significant                     non-credible
4  NA              NA                                  NA
5  NA              NA                                  NA
6  NA              NA                                  NA
7  NA              NA                                  NA
8  NA              NA                                  NA
9  NA              NA                                  NA
10 NA              NA                                  NA
11 NA              NA                                  NA
12 NA              NA                                  NA
13 NA              NA                                  NA
14 NA              NA                                  NA
15 NA              NA                                  NA
16 NA              NA                                  NA
17 NA              NA                                  NA
18 NA              NA                                  NA
19 NA              NA                                  NA
20 NA              NA                                  NA
21 NA              NA                                  NA
22 NA              NA                                  NA
23 NA              NA                                  NA
24 NA              NA                                  NA
25 NA              NA                                  NA
26 NA              NA                                  NA
27 NA              NA                                  NA
28 NA              NA                                  NA
29 NA              NA                                  NA
30 NA              NA                                  NA
31 NA              NA                                  NA
32 NA              NA                                  NA
33 NA              NA                                  NA
34 NA              NA                                  NA
35 NA              NA                                  NA
36 NA              NA                                  NA
37 NA              NA                                  NA
38 NA              NA                                  NA
39 NA              NA                                  NA
40 NA              NA                                  NA
41 NA              NA                                  NA
   testes_specificity ⋯ Eusperm_Spermatids Parasperm_Early_Spermatocytes
1  other              ⋯ not deg            deg
2  testes             ⋯ not deg            not deg
3  other              ⋯ not deg            not deg
4  NA                 ⋯ NA                 NA
5  NA                 ⋯ NA                 NA
6  NA                 ⋯ NA                 NA
7  NA                 ⋯ NA                 NA
8  NA                 ⋯ NA                 NA
9  NA                 ⋯ NA                 NA
10 NA                 ⋯ NA                 NA
11 NA                 ⋯ NA                 NA
12 NA                 ⋯ NA                 NA
13 NA                 ⋯ NA                 NA
14 NA                 ⋯ NA                 NA
15 NA                 ⋯ NA                 NA
16 NA                 ⋯ NA                 NA
17 NA                 ⋯ NA                 NA
18 NA                 ⋯ NA                 NA
19 NA                 ⋯ NA                 NA
20 NA                 ⋯ NA                 NA
21 NA                 ⋯ NA                 NA
22 NA                 ⋯ NA                 NA
23 NA                 ⋯ NA                 NA
24 NA                 ⋯ NA                 NA
25 NA                 ⋯ NA                 NA
26 NA                 ⋯ NA                 NA
27 NA                 ⋯ NA                 NA
28 NA                 ⋯ NA                 NA
29 NA                 ⋯ NA                 NA
30 NA                 ⋯ NA                 NA
31 NA                 ⋯ NA                 NA
32 NA                 ⋯ NA                 NA
33 NA                 ⋯ NA                 NA
34 NA                 ⋯ NA                 NA
35 NA                 ⋯ NA                 NA
36 NA                 ⋯ NA                 NA
37 NA                 ⋯ NA                 NA
38 NA                 ⋯ NA                 NA
39 NA                 ⋯ NA                 NA
40 NA                 ⋯ NA                 NA
41 NA                 ⋯ NA                 NA
   Parasperm_Late_Spermatocytes Parasperm_Spermatids dmel.x paralog.x score.x
1  not deg                      not deg              Obp44a 1:1       18154
2  not deg                      not deg              Obp50b 1:1        6996
3  not deg                      not deg              Obp99a 1:1       18152
4  NA                           NA                   NA     NA           NA
5  NA                           NA                   NA     NA           NA
6  NA                           NA                   NA     NA           NA
7  NA                           NA                   NA     NA           NA
8  NA                           NA                   NA     NA           NA
9  NA                           NA                   NA     NA           NA
10 NA                           NA                   NA     NA           NA
11 NA                           NA                   NA     NA           NA
12 NA                           NA                   NA     NA           NA
13 NA                           NA                   NA     NA           NA
14 NA                           NA                   NA     NA           NA
15 NA                           NA                   NA     NA           NA
16 NA                           NA                   NA     NA           NA
17 NA                           NA                   NA     NA           NA
18 NA                           NA                   NA     NA           NA
19 NA                           NA                   NA     NA           NA
20 NA                           NA                   NA     NA           NA
21 NA                           NA                   NA     NA           NA
22 NA                           NA                   NA     NA           NA
23 NA                           NA                   NA     NA           NA
24 NA                           NA                   NA     NA           NA
25 NA                           NA                   NA     NA           NA
26 NA                           NA                   NA     NA           NA
27 NA                           NA                   NA     NA           NA
28 NA                           NA                   NA     NA           NA
29 NA                           NA                   NA     NA           NA
30 NA                           NA                   NA     NA           NA
31 NA                           NA                   NA     NA           NA
32 NA                           NA                   NA     NA           NA
33 NA                           NA                   NA     NA           NA
34 NA                           NA                   NA     NA           NA
35 NA                           NA                   NA     NA           NA
36 NA                           NA                   NA     NA           NA
37 NA                           NA                   NA     NA           NA
38 NA                           NA                   NA     NA           NA
39 NA                           NA                   NA     NA           NA
40 NA                           NA                   NA     NA           NA
41 NA                           NA                   NA     NA           NA
   dmel.y  paralog.y score.y
1  Obp44a  1:1       18154
2  Obp50b  1:1        6996
3  Obp99a  1:1       18152
4  Obp99b  1:1       28366
5  Obp99d  1:1       18156
6  Obp99c  1:1       35000
7  Obp83cd 1:1       10453
8  Obp83b  1:1       24621
9  Obp83a  1:1       24617
10 Obp93a  1:1       22902
11 Obp85a  1:1        3975
12 Obp84a  1:1       10633
13 Obp59a  1:1        8110
14 Obp58b  1:1       22897
15 Obp58c  1:1       22900
16 Obp58d  1:1       29699
17 Obp50e  1:1       22899
18 Obp50d  1:1       22907
19 Obp50c  1:1       22903
20 Obp50a  1:1        7019
21 Obp46a  1:1        6583
22 Obp57c  1:1        7888
23 Obp57e  1:1       23177
24 Obp49a  1:1       22898
25 Obp56a  1:1        7701
26 Obp56b  1:1        7699
27 Obp56c  1:1        7667
28 Obp56d  1:1        7693
29 Obp56e  1:1        7700
30 Obp56g  1:1        7690
31 Obp56h  1:1       26906
32 Obp47b  1:1       22901
33 Obp47a  1:1       29829
34 Obp28a  1:1       31031
35 Obp8a   1:1       19101
36 Obp19a  1:1       26409
37 Obp19b  1:1       19913
38 Obp19c  1:1       19912
39 Obp19d  1:1       31030
40 Obp69a  1:1        7692
41 Obp73a  1:1        9820